const STORAGE_KEY='ira_radio_game_center_v1';
const APP_VERSION='1.5.0';
const DEFAULT_SCHEDULE=[
 {week:1,date:'2026-08-28',time:'7:30 PM',opponent:'Roby Lions',rank:80,site:'Away',district:false},
 {week:2,date:'2026-09-04',time:'7:30 PM',opponent:'Jayton Jaybirds',rank:13,site:'Home',district:false},
 {week:3,date:'2026-09-11',time:'7:30 PM',opponent:'Garden City Bearkats',rank:42,site:'Away',district:false},
 {week:4,date:'2026-09-18',time:'7:00 PM',opponent:'Abilene Christian Panthers',rank:96,site:'Home',district:false},
 {week:5,date:'2026-09-25',time:'7:30 PM',opponent:'Meadow Broncos',rank:130,site:'Away',district:false},
 {week:6,date:'',time:'',opponent:'OPEN / BYE',rank:null,site:'',district:false},
 {week:7,date:'2026-10-09',time:'7:30 PM',opponent:'Sands Mustangs',rank:23,site:'Home',district:true},
 {week:8,date:'2026-10-16',time:'7:00 PM',opponent:'Klondike Cougars',rank:16,site:'Away',district:true},
 {week:9,date:'2026-10-23',time:'7:30 PM',opponent:"O'Donnell Eagles",rank:86,site:'Home',district:true},
 {week:10,date:'2026-10-30',time:'7:00 PM',opponent:'Borden County Coyotes',rank:3,site:'Away',district:true},
 {week:11,date:'2026-11-06',time:'7:00 PM',opponent:'Westbrook Wildcats',rank:24,site:'Home',district:true}
];
const HISTORY=[{year:2025,record:'8-3'},{year:2024,record:'7-4'},{year:2023,record:'6-4'},{year:2022,record:'8-3'},{year:2021,record:'7-3'},{year:2020,record:'8-3'},{year:2019,record:'11-1'},{year:2018,record:'10-1'},{year:2014,record:'12-1'},{year:2013,record:'12-1'},{year:2011,record:'12-1'},{year:2010,record:'12-1'}];
const blankTeamStats=()=>({rushYds:0,passYds:0,firstDowns:0,turnovers:0,plays:0,score:0,possessions:0});
const initialState=()=>({
 version:5, playerUse:{ira:{},opp:{}}, opponentInfo:{color:'#667085'}, pregameData:{}, settings:{syncUrl:'',publishKey:'IRA-RADIO-2026-8f3a1d',listenUrl:''}, teamInfo:{name:'Ira Bulldogs',rank:25,leagueRank:16,rating:315.75,league:'UIL Division I',district:'District 5',coach:'Jess Wall',stadium:'Ira Bulldogs Field',colors:'Black and Orange',updated:null},
 schedule:DEFAULT_SCHEDULE, history:HISTORY, selectedWeek:1,
 games:{},
 rosters:{ira:[],opp:[]}
});
let state=load();
let talkingIndex=0;

function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return x?mergeState(initialState(),x):initialState()}catch{return initialState()}}
function mergeState(base,saved){return {...base,...saved,settings:{...base.settings,...(saved.settings||{})},teamInfo:{...base.teamInfo,...(saved.teamInfo||{})},rosters:{...base.rosters,...(saved.rosters||{})}}}
function save(msg='Saved locally'){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));const e=document.getElementById('saveState');if(e)e.textContent=msg;renderAll();schedulePublish()}
function currentSchedule(){return state.schedule.find(x=>x.week===Number(state.selectedWeek))||state.schedule[0]}
function gameKey(){return `2026-w${state.selectedWeek}`}
function ensureGame(){const s=currentSchedule();if(!state.games[gameKey()]) state.games[gameKey()]={week:s.week,opponent:s.opponent,date:s.date,time:s.time,site:s.site,quarter:1,clock:'10:00',down:1,toGo:15,ballOn:'Own 20',possession:'ira',iraScore:0,oppScore:0,plays:[],notes:'',publicUpdate:'',final:false,created:new Date().toISOString()};return state.games[gameKey()]}

let publishTimer=null;
function publicPayload(){
 const g=ensureGame(),st=calc();
 const leaders=(team,key,attKey)=>Object.entries(st[team].players||{}).map(([id,x])=>({id,...x})).sort((a,b)=>(b[key]||0)-(a[key]||0)).filter(x=>(x[key]||0)>0).slice(0,3).map(x=>({name:playerName(team,x.id),value:x[key]||0,attempts:attKey?(x[attKey]||0):undefined}));
 return {version:2,updated:new Date().toISOString(),broadcasterState:cloudState(),team:{name:state.teamInfo.name,rank:state.teamInfo.rank},game:{week:g.week,opponent:g.opponent,date:g.date,time:g.time,site:g.site,quarter:g.quarter,clock:g.clock,down:g.down,toGo:g.toGo,ballOn:g.ballOn,possession:g.possession,iraScore:g.iraScore,oppScore:g.oppScore,final:g.final},stats:{ira:{rushYds:st.ira.rushYds,passYds:st.ira.passYds,totalYds:st.ira.rushYds+st.ira.passYds,firstDowns:st.ira.firstDowns,turnovers:st.ira.turnovers,plays:st.ira.plays},opp:{rushYds:st.opp.rushYds,passYds:st.opp.passYds,totalYds:st.opp.rushYds+st.opp.passYds,firstDowns:st.opp.firstDowns,turnovers:st.opp.turnovers,plays:st.opp.plays}},leaders:{rushing:leaders('ira','rushYds','rushAtt'),passing:leaders('ira','passYds','passAtt'),receiving:leaders('ira','recYds','rec')},plays:g.plays.slice(-100).map((p,i)=>({seq:g.plays.length-Math.min(100,g.plays.length)+i+1,text:describePlay(p),at:p.at||null})),listenUrl:state.settings.listenUrl||''};
}
function cloudState(){return {version:state.version,selectedWeek:state.selectedWeek,games:state.games,rosters:state.rosters,settings:{listenUrl:state.settings.listenUrl||''},teamInfo:state.teamInfo,schedule:state.schedule,history:state.history,cloudUpdated:new Date().toISOString()}}
function schedulePublish(){clearTimeout(publishTimer);publishTimer=setTimeout(publishPublic,900)}
async function loadCloudGame(){
 const url=(state.settings.syncUrl||'').trim(),key=(state.settings.publishKey||'').trim();
 if(!url||!key){toast('Add the Apps Script URL in Settings');return}
 if(!navigator.onLine){toast('Internet connection needed to load cloud game');return}
 try{
  const x=await jsonp(url,{action:'state',key,_:Date.now()});
  if(!x||!x.ok||!x.data)throw new Error((x&&x.error)||'No cloud game found');
  const keep={syncUrl:state.settings.syncUrl,publishKey:state.settings.publishKey,listenUrl:state.settings.listenUrl};
  state=mergeState(initialState(),x.data);state.settings={...state.settings,...keep};save('Loaded from cloud');toast('Current game loaded from cloud');
 }catch(e){console.error('Cloud load failed',e);toast('Could not load cloud game')}
}
function jsonp(url,params={}){
 return new Promise((resolve,reject)=>{
  const cb='iraCloud_'+Date.now()+'_'+Math.random().toString(36).slice(2);
  const script=document.createElement('script');
  const cleanup=()=>{try{delete window[cb]}catch(_){window[cb]=undefined}script.remove()};
  const timer=setTimeout(()=>{cleanup();reject(new Error('Cloud request timed out'))},12000);
  window[cb]=data=>{clearTimeout(timer);cleanup();resolve(data)};
  const q=new URLSearchParams({...params,callback:cb});
  script.src=url+(url.includes('?')?'&':'?')+q.toString();
  script.onerror=()=>{clearTimeout(timer);cleanup();reject(new Error('Cloud request failed'))};
  document.head.appendChild(script);
 });
}
async function publishPublic(){
 const url=(state.settings.syncUrl||'').trim(),key=(state.settings.publishKey||'').trim();
 const status=document.getElementById('publicStatus');
 if(!url||!key){if(status)status.textContent='Public: setup needed';return}
 if(!navigator.onLine){if(status)status.textContent='Public: queued offline';return}
 try{if(status)status.textContent='Public: syncing…';const body=new URLSearchParams({action:'publish',key,payload:JSON.stringify(publicPayload())});await fetch(url,{method:'POST',mode:'no-cors',body});if(status)status.textContent='Public: updated';}
 catch(e){if(status)status.textContent='Public: queued';}
}
window.addEventListener('online',()=>schedulePublish());

function fmtDate(d){if(!d)return 'Open week';return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function playerName(team,id){const p=(state.rosters[team]||[]).find(p=>p.id===id);return p?`#${p.number} ${p.name}`:'Unknown player'}
function teamLabel(t){return t==='ira'?'Ira':'Opponent'}
function uid(){return Math.random().toString(36).slice(2,10)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}

function calc(){const g=ensureGame();const teams={ira:{...blankTeamStats(),players:{}},opp:{...blankTeamStats(),players:{}}};
 const pstat=(t,id)=>{if(!id)return null;if(!teams[t].players[id])teams[t].players[id]={rushAtt:0,rushYds:0,rushTD:0,passAtt:0,passComp:0,passYds:0,passTD:0,int:0,rec:0,recYds:0,recTD:0,points:0,tackles:0,sacks:0,defInt:0,fumbleRec:0};return teams[t].players[id]};
 for(const p of g.plays){const t=teams[p.team],other=teams[p.team==='ira'?'opp':'ira'];if(!t)continue;
   if(['run','pass','sack'].includes(p.type))t.plays++;
   if(p.type==='run'){t.rushYds+=p.yards||0;const ps=pstat(p.team,p.runner);if(ps){ps.rushAtt++;ps.rushYds+=p.yards||0}if(p.firstDown)t.firstDowns++;if(p.touchdown){if(ps){ps.rushTD++;ps.points+=6}t.score+=6}}
   if(p.type==='pass'){const qb=pstat(p.team,p.passer);if(qb)qb.passAtt++;if(p.complete){if(qb){qb.passComp++;qb.passYds+=p.yards||0}t.passYds+=p.yards||0;const r=pstat(p.team,p.receiver);if(r){r.rec++;r.recYds+=p.yards||0}if(p.firstDown)t.firstDowns++;if(p.touchdown){if(qb)qb.passTD++;if(r){r.recTD++;r.points+=6}t.score+=6}}if(p.interception){if(qb)qb.int++;t.turnovers++;other.possessions++}}
   if(p.type==='sack'){t.passYds+=p.yards||0}
   if(p.type==='turnover'){t.turnovers++;other.possessions++}
   const defTeam=p.team==='ira'?'opp':'ira';
   if(p.tacklers?.length){p.tacklers.forEach(id=>{const ds=pstat(defTeam,id);if(ds)ds.tackles++})}
   if(p.interception&&p.interceptedBy){const ds=pstat(defTeam,p.interceptedBy);if(ds)ds.defInt++}
   if(p.turnover&&p.recoveredBy){const ds=pstat(defTeam,p.recoveredBy);if(ds)ds.fumbleRec++}
   if(p.type==='turnover'&&p.defender){const ds=pstat(defTeam,p.defender);if(ds){if(String(p.turnoverType).toLowerCase().includes('interception'))ds.defInt++;if(String(p.turnoverType).toLowerCase().includes('fumble'))ds.fumbleRec++}}
   if(p.type==='score'){t.score+=p.points||0;const ps=pstat(p.team,p.scorer);if(ps)ps.points+=p.points||0}
   if(p.type==='possession')t.possessions++;
 }
 // Manual scoreboard remains authoritative; play-derived score is useful but not forced.
 teams.ira.score=g.iraScore;teams.opp.score=g.oppScore;return teams;
}

function renderAll(){renderPregame();renderLive();renderStats();renderHalftime();renderPostgame();renderRosters()}
function renderPregame(){const s=currentSchedule(),g=ensureGame();const tp=talkingPoints();const scheduleRows=state.schedule.map(x=>`<div class="schedule-row ${x.week===Number(state.selectedWeek)?'current':''}" data-week="${x.week}"><div><strong>Wk ${x.week}</strong><div class="small muted">${fmtDate(x.date)}</div></div><div><strong>${esc(x.opponent)}</strong><div class="small muted">${esc(x.time||'')}</div></div><div>${x.rank?`<span class="rank">#${x.rank}</span>`:''}</div><div class="location">${esc(x.site)}${x.district?' • District':''}</div></div>`).join('');
 document.getElementById('pregame').innerHTML=`
 <div class="card hero"><div class="hero-row"><div class="matchup"><div class="eyebrow">WEEK ${s.week} • PREGAME</div><h2>IRA vs ${esc(s.opponent.replace(/\s+(Lions|Jaybirds|Bearkats|Panthers|Broncos|Mustangs|Cougars|Eagles|Coyotes|Wildcats)$/,''))}</h2><div class="matchup-meta"><span class="pill">${fmtDate(s.date)} ${esc(s.time)}</span><span class="pill">${esc(s.site)}</span>${s.district?'<span class="pill">DISTRICT</span>':''}</div></div><div><div class="kicker">SixManFootball snapshot</div><div style="font-size:2.1rem;font-weight:900">#${state.teamInfo.rank}</div><div class="muted" style="color:#bbb">Ira overall rank</div></div></div></div>
 <div class="grid two" style="margin-top:16px"><div class="card"><div class="inline" style="justify-content:space-between"><h2>2026 Schedule</h2><button id="syncBtn">Sync SixManFootball</button></div><div class="schedule-list">${scheduleRows}</div></div>
 <div class="grid"><div class="card"><h2>Broadcast Talking Point</h2><div class="talking-point">${esc(tp[talkingIndex%tp.length]||'Add roster and game data to create talking points.')}</div><div class="talking-controls"><button id="nextTalkingBtn">Next Talking Point</button><button class="ghost" id="copyTalkingBtn">Copy</button></div></div>
 <div class="card"><h3>Ira Program Snapshot</h3><div class="summary-grid"><div class="summary-item"><span class="kicker">Coach</span><strong>${esc(state.teamInfo.coach)}</strong></div><div class="summary-item"><span class="kicker">League</span><strong>${esc(state.teamInfo.league)}</strong></div><div class="summary-item"><span class="kicker">District</span><strong>${esc(state.teamInfo.district)}</strong></div><div class="summary-item"><span class="kicker">Rating</span><strong>${state.teamInfo.rating}</strong></div></div><p class="small muted" style="margin-top:10px">Cached data${state.teamInfo.updated?' • updated '+new Date(state.teamInfo.updated).toLocaleString():''}. The broadcast tools continue working offline.</p></div></div></div>`;
 document.querySelectorAll('.schedule-row').forEach(el=>el.onclick=()=>{state.selectedWeek=Number(el.dataset.week);save()});
 document.getElementById('nextTalkingBtn').onclick=()=>{talkingIndex++;renderPregame()};
 document.getElementById('copyTalkingBtn').onclick=()=>navigator.clipboard?.writeText(tp[talkingIndex%tp.length]||'').then(()=>toast('Talking point copied'));
 document.getElementById('syncBtn').onclick=syncSixMan;
}
function talkingPoints(){const s=currentSchedule(),games=Object.values(state.games),completed=games.filter(g=>g.final);const pts=[];
 pts.push(`Ira enters 2026 ranked #${state.teamInfo.rank} overall by SixManFootball with a rating of ${state.teamInfo.rating}.`);
 pts.push(`Tonight's opponent is ${s.opponent}${s.rank?`, currently listed #${s.rank}`:''}. This is a ${s.site.toLowerCase()||'scheduled'} game for Ira${s.district?' and a district matchup':''}.`);
 pts.push(`Jess Wall is the Ira head coach. The Bulldogs compete in ${state.teamInfo.league}, ${state.teamInfo.district}.`);
 pts.push(`Ira finished 8-3 in 2025. The program also posted 12-1 seasons in 2010, 2011, 2013 and 2014.`);
 const next=state.schedule.find(x=>x.week>s.week&&x.opponent!=='OPEN / BYE');if(next)pts.push(`Next up for Ira: ${next.opponent} on ${fmtDate(next.date)} at ${next.time}, ${next.site.toLowerCase()}.`);
 if(completed.length){const pf=completed.reduce((a,g)=>a+g.iraScore,0),pa=completed.reduce((a,g)=>a+g.oppScore,0);pts.push(`Through ${completed.length} completed game${completed.length===1?'':'s'} tracked here, Ira is averaging ${(pf/completed.length).toFixed(1)} points and allowing ${(pa/completed.length).toFixed(1)}.`)}
 return pts;
}
async function syncSixMan(){const url=(state.settings.syncUrl||'').trim();if(!url){toast('Add the Apps Script sync URL in Settings');document.getElementById('settingsDialog').showModal();return}const btn=document.getElementById('syncBtn');btn.disabled=true;btn.textContent='Syncing…';try{const r=await fetch(url+(url.includes('?')?'&':'?')+'action=team');if(!r.ok)throw new Error('Sync failed');const data=await r.json();if(data.schedule?.length>=8)state.schedule=data.schedule;else if(data.schedule?.length)toast('Sync looked incomplete — full cached schedule kept');if(data.teamInfo)state.teamInfo={...state.teamInfo,...data.teamInfo,updated:new Date().toISOString()};save('Synced');toast('SixManFootball data refreshed')}catch(e){toast('Could not sync; cached data kept')}finally{renderPregame()}}

function toGoOptions(v){const vals=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,20,25,30];return vals.map(x=>`<option value="${x}" ${String(v)===String(x)?'selected':''}>${x}</option>`).join('')+`<option value="Goal" ${String(v).toLowerCase()==='goal'?'selected':''}>Goal</option>`}
function renderLive(){const g=ensureGame(),st=calc(),diff=Math.abs(g.iraScore-g.oppScore),leader=g.iraScore===g.oppScore?'Tied':(g.iraScore>g.oppScore?'Ira':'Opponent'),secondHalf=Number(g.quarter)>=3,marginClass=secondHalf&&diff>=45?'mercy':secondHalf&&diff>=40?'warning':'';document.getElementById('live').innerHTML=`<div class="grid live-layout">
 <div class="grid"><div class="card hero"><div class="eyebrow">LIVE GAME • WEEK ${g.week}</div><div class="scoreboard"><button type="button" class="score-team" data-score-team="ira" aria-label="Edit Ira score"><div class="team-name">IRA</div><div class="team-score">${g.iraScore}</div><div class="score-tap-hint">Tap score</div></button><div class="score-dash">–</div><button type="button" class="score-team" data-score-team="opp" aria-label="Edit opponent score"><div class="team-name">${esc(g.opponent)}</div><div class="team-score">${g.oppScore}</div><div class="score-tap-hint">Tap score</div></button></div><div class="margin-bar"><span class="margin-pill ${marginClass}">${leader==='Tied'?'Tied':`${leader} +${diff}`}</span><span class="margin-sep">•</span>${secondHalf&&diff>=45?'<span class="margin-pill mercy">45-POINT MARGIN REACHED</span>':secondHalf&&diff>=40?`<span class="margin-pill warning">${45-diff} point${45-diff===1?'':'s'} from 45</span>`:''}</div></div>
 <div class="card offense-card ${g.possession==='ira'?'ira-offense':'opp-offense'}" style="--opp-color:${opponentColor()}"><div class="offense-banner">${g.possession==='ira'?'IRA OFFENSE':esc(g.opponent.toUpperCase())+' OFFENSE'}</div><div class="cloud-load-row"><button type="button" class="dark" id="loadCloudBtn">☁ Load Current Game from Cloud</button><span class="cloud-load-status">Use this when switching broadcaster devices.</span></div><div class="possession"><button data-pos="ira" class="${g.possession==='ira'?'active':''}">Ira Ball</button><button data-pos="opp" class="${g.possession==='opp'?'active':''}">Opponent Ball</button></div><div class="game-meta"><label>Quarter<select id="quarterSel">${[1,2,3,4,5].map(q=>`<option ${g.quarter===q?'selected':''}>${q}</option>`).join('')}</select></label><label>Clock<input id="clockInput" value="${esc(g.clock)}"></label><label>Down<select id="downSel">${[1,2,3,4].map(x=>`<option ${g.down===x?'selected':''}>${x}</option>`).join('')}</select></label><label>To Go<select id="toGoInput">${toGoOptions(g.toGo)}</select></label><label>Ball Side<select id="ballSideInput"><option ${String(g.ballOn).startsWith('Own')?'selected':''}>Own</option><option ${String(g.ballOn).startsWith('Opp')?'selected':''}>Opp</option></select></label><label>Yard Line<input id="ballYardInput" type="number" inputmode="numeric" min="1" max="40" value="${ballParts(g.ballOn).yard}"></label></div>
 <div class="live-controls"><button class="run" data-play="run">RUN</button><button class="pass" data-play="pass">PASS</button><button data-play="sack">SACK</button><button class="penalty" data-play="penalty">PENALTY</button><button data-play="turnover">TURNOVER</button><button class="score" data-play="score">SCORE</button><button data-play="possession">NEW DRIVE</button><button class="dark" id="undoBtn">UNDO LAST</button></div></div>
 <div class="card"><div class="inline"><div><h2>Play-by-Play</h2><div class="small muted">Newest play first</div></div><button class="ghost" id="clearGameBtn">Reset Game</button></div><div class="play-log">${[...g.plays].reverse().map((p,i)=>`<div class="play-row"><div class="seq">#${g.plays.length-i}</div><div>${esc(describePlay(p))}</div><button class="ghost" data-delplay="${p.id}">Delete</button></div>`).join('')||'<p class="muted">No plays entered yet.</p>'}</div></div></div>
 <div class="grid"><div class="card"><div class="inline"><h2>Radio Dashboard</h2><button class="ghost" id="loadCloudBtn">Load Current Game from Cloud</button></div><div class="stat-strip"><div class="stat-box"><strong>${st.ira.rushYds}</strong><span>Rush yds</span></div><div class="stat-box"><strong>${st.ira.passYds}</strong><span>Pass yds</span></div><div class="stat-box"><strong>${st.ira.rushYds+st.ira.passYds}</strong><span>Total yds</span></div><div class="stat-box"><strong>${st.ira.firstDowns}</strong><span>1st downs</span></div><div class="stat-box"><strong>${st.ira.turnovers}</strong><span>Turnovers</span></div><div class="stat-box"><strong>${st.ira.plays?((st.ira.rushYds+st.ira.passYds)/st.ira.plays).toFixed(1):'0.0'}</strong><span>Yds/play</span></div></div></div>
 <div class="card"><h2>Broadcast Notes</h2>${broadcastNotes(st).map(x=>`<div class="broadcast-note">${esc(x)}</div>`).join('')||'<p class="muted">Notes appear as you enter plays.</p>'}</div>
 <div class="card"><h2>Ira Leaders</h2>${leadersTable(st.ira.players)}</div>
 <div class="card"><h2>Ira Defense</h2>${defenseTable(st.ira.players)}</div>
 <div class="card"><h2>Score Controls</h2><div class="grid two"><label>Ira score<input id="iraScore" type="number" value="${g.iraScore}"></label><label>Opponent score<input id="oppScore" type="number" value="${g.oppScore}"></label></div></div></div></div>`;
 document.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{g.possession=b.dataset.pos;save()});document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>openPlay(b.dataset.play));
 ['quarterSel','clockInput','downSel','toGoInput','iraScore','oppScore'].forEach(id=>{const el=document.getElementById(id);if(!el)return;const commit=e=>{const map={quarterSel:'quarter',clockInput:'clock',downSel:'down',toGoInput:'toGo',iraScore:'iraScore',oppScore:'oppScore'};let v=e.target.value;if(['quarterSel','downSel','iraScore','oppScore'].includes(id))v=Number(v);if(id==='toGoInput'&&v!=='Goal')v=Number(v);g[map[id]]=v;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));schedulePublish()};el.onchange=commit;if(id==='clockInput')el.oninput=commit});const saveBall=()=>{g.ballOn=document.getElementById('ballSideInput').value+' '+Math.max(1,Math.min(40,Number(document.getElementById('ballYardInput').value||20)));if(g.down===1&&distanceToGoal(g.ballOn)<15)g.toGo='Goal';save()};document.getElementById('ballSideInput').onchange=saveBall;document.getElementById('ballYardInput').onchange=saveBall;
 document.querySelectorAll('#loadCloudBtn').forEach(x=>x.onclick=loadCloudGame);document.getElementById('undoBtn').onclick=()=>{if(g.plays.length){const p=g.plays.pop();if(p.touchdown){if(p.team==='ira')g.iraScore=Math.max(0,g.iraScore-6);else g.oppScore=Math.max(0,g.oppScore-6)}if(p.type==='score'&&p.points){if(p.team==='ira')g.iraScore=Math.max(0,g.iraScore-p.points);else g.oppScore=Math.max(0,g.oppScore-p.points)}rebuildSituation(p);save();toast('Last play undone')}};document.querySelectorAll('[data-delplay]').forEach(b=>b.onclick=()=>{g.plays=g.plays.filter(p=>p.id!==b.dataset.delplay);save()});
 document.querySelectorAll('[data-score-team]').forEach(b=>b.onclick=()=>openScoreDialog(b.dataset.scoreTeam));
 const cloudBtn=document.getElementById('loadCloudBtn');if(cloudBtn)cloudBtn.onclick=async()=>{cloudBtn.disabled=true;cloudBtn.textContent='Loading…';await loadCloudGame();};
 document.getElementById('clearGameBtn').onclick=()=>{if(confirm('Reset this game? This removes all plays and scores for the selected week.')){delete state.games[gameKey()];save();toast('Game reset')}};
}
let scoreEditTeam='ira';
function openScoreDialog(team){scoreEditTeam=team==='opp'?'opp':'ira';const g=ensureGame(),name=scoreEditTeam==='ira'?'Ira':g.opponent,current=scoreEditTeam==='ira'?g.iraScore:g.oppScore;document.getElementById('scoreDialogTitle').textContent=name+' Score';document.getElementById('exactScoreInput').value=current;document.getElementById('scoreDialog').showModal()}
function updateQuickScore(delta){const g=ensureGame(),key=scoreEditTeam==='ira'?'iraScore':'oppScore';g[key]=Math.max(0,Number(g[key]||0)+Number(delta||0));save();document.getElementById('scoreDialog').close();toast(`${scoreEditTeam==='ira'?'Ira':'Opponent'} score: ${g[key]}`)}
document.querySelectorAll('[data-score-add]').forEach(b=>b.onclick=()=>updateQuickScore(Number(b.dataset.scoreAdd)));
document.getElementById('setExactScoreBtn').onclick=()=>{const g=ensureGame(),key=scoreEditTeam==='ira'?'iraScore':'oppScore',v=Math.max(0,Number(document.getElementById('exactScoreInput').value||0));g[key]=v;save();document.getElementById('scoreDialog').close();toast(`${scoreEditTeam==='ira'?'Ira':'Opponent'} score: ${v}`)};

function playerOptions(team,selected=''){const list=state.rosters[team]||[],use=(state.playerUse||{})[team]||{};return `<option value="">Select player (optional)</option>`+list.slice().sort((a,b)=>(use[b.id]||0)-(use[a.id]||0)||Number(a.number)-Number(b.number)).map(p=>`<option value="${p.id}" ${selected===p.id?'selected':''}>#${esc(p.number)} ${esc(p.name)}</option>`).join('')}
function quickYards(){return `<div class="quick-yards"><button type="button" data-yard="-5">-5</button><button type="button" data-yard="0">0</button><button type="button" data-yard="5">5</button><button type="button" data-yard="10">10</button><button type="button" data-yard="15">15</button><button type="button" data-yard="20">20</button></div>`}
function tackleFields(defTeam){if(defTeam!=='ira')return '';const players=(state.rosters.ira||[]).slice().sort((a,b)=>Number(a.number)-Number(b.number));return `<div class="defense-box"><div class="kicker">IRA DEFENSE • OPTIONAL</div><label>Tackle credit<select name="tackleMode"><option value="">Skip tackle</option><option value="single">Single player</option><option value="multiple">Multiple / group tackle</option></select></label><div class="tackler-picks">${players.map(p=>`<label class="check-pill"><input type="checkbox" name="tackler" value="${p.id}"> #${esc(p.number)} ${esc(p.name)}</label>`).join('')||'<span class="muted small">Add the Ira roster to select tacklers. You can still save a group tackle without names.</span>'}</div></div>`}
function openPlay(type){const g=ensureGame(),team=g.possession,defTeam=team==='ira'?'opp':'ira';const d=document.getElementById('playDialog'),fields=document.getElementById('playFormFields');document.getElementById('playDialogTitle').textContent=type[0].toUpperCase()+type.slice(1);document.getElementById('playDialogEyebrow').textContent=`${teamLabel(team).toUpperCase()} OFFENSE`;
 let html=`<input type="hidden" name="type" value="${type}"><input type="hidden" name="team" value="${team}">`;
 if(type==='run')html+=`<div class="form-grid"><label>Ball carrier<select name="runner">${playerOptions(team)}</select></label><label>Exact yards<input class="yards-input" name="yards" type="number" inputmode="numeric" placeholder="Type yards"></label><input type="hidden" name="result" value="normal"><div><span class="kicker">RESULT</span><div class="result-buttons"><button type="button" data-result="normal" class="selected">Normal</button><button type="button" data-result="td">Touchdown</button><button type="button" data-result="fumble">Fumble</button></div></div></div>${quickYards()}${tackleFields(defTeam)}<div class="defense-box"><label>Fumble recovered by (optional)<select name="recoveredBy">${playerOptions(defTeam)}</select></label></div>`;
 if(type==='pass')html+=`<div class="form-grid"><label>Passer<select name="passer">${playerOptions(team)}</select></label><label>Receiver<select name="receiver">${playerOptions(team)}</select></label><input type="hidden" name="result" value="complete"><div><span class="kicker">RESULT</span><div class="result-buttons"><button type="button" data-result="complete" class="selected">Complete</button><button type="button" data-result="incomplete">Incomplete</button><button type="button" data-result="int">Intercepted</button><button type="button" data-result="td">Touchdown</button></div></div><label>Exact yards<input class="yards-input" name="yards" type="number" inputmode="numeric" placeholder="Type yards"></label></div>${quickYards()}${tackleFields(defTeam)}<div class="defense-box"><label>Intercepted by (optional)<select name="interceptedBy">${playerOptions(defTeam)}</select></label></div>`;
 if(type==='sack')html+=`<div class="form-grid"><label>Yards lost<input class="yards-input" name="yards" type="number" inputmode="numeric" min="0" placeholder="6"></label></div><div class="quick-yards">${[3,5,7,10].map(x=>`<button type="button" data-yard="${x}">${x}</button>`).join('')}</div>${tackleFields(defTeam)}`;
 if(type==='penalty')html+=`<div class="form-grid"><label>Penalty<input name="penalty" placeholder="Holding"></label><label>Yards<input class="yards-input" name="yards" type="number" inputmode="numeric" placeholder="5"></label><label>On<select name="penaltyOn"><option value="ira">Ira</option><option value="opp">Opponent</option></select></label></div>${quickYards()}`;
 if(type==='turnover')html+=`<div class="form-grid"><label>Type<select name="turnoverType"><option>Fumble</option><option>Interception</option><option>Downs</option></select></label><label>Defender credited (optional)<select name="defender">${playerOptions(defTeam)}</select></label></div>`;
 if(type==='score')html+=`<div class="form-grid"><label>Scorer<select name="scorer">${playerOptions(team)}</select></label><label>Points<select name="points"><option value="6">Touchdown • 6</option><option value="2">Kick PAT • 2</option><option value="1">Run/Pass PAT • 1</option><option value="4">Field Goal • 4</option><option value="2">Safety • 2</option></select></label><label>Description<input name="description" placeholder="PAT kick good"></label></div>`;
 if(type==='possession')html+=`<p>This records a new possession/drive for ${teamLabel(team)}.</p>`;
 html+=`<label style="display:grid;gap:6px;margin-top:12px">Radio note (optional)<input name="note" placeholder="Great block by #12, injury timeout, etc."></label>`;fields.innerHTML=html;
 fields.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{fields.querySelector('[name=result]').value=b.dataset.result;fields.querySelectorAll('[data-result]').forEach(x=>x.classList.toggle('selected',x===b))});fields.querySelectorAll('[data-yard]').forEach(b=>b.onclick=()=>{const input=fields.querySelector('.yards-input');if(input){input.value=b.dataset.yard;input.blur()}});fields.querySelectorAll('.yards-input').forEach(i=>i.addEventListener('focus',()=>i.select()));d.showModal();
}
function resetSeries(g){g.down=1;g.toGo=15}
function advanceSituation(p){const g=ensureGame();if(p.type==='score'||p.type==='possession')return;if(p.type==='penalty'){const againstOffense=p.penaltyOn===g.possession;const y=Math.abs(Number(p.yards||0));if(String(g.toGo).toLowerCase()!=='goal')g.toGo=Math.max(1,Number(g.toGo||15)+(againstOffense?y:-y));return;}if(p.touchdown){resetSeries(g);return}if(p.type==='turnover'||p.interception||p.turnover){resetSeries(g);return}
 const oldDown=Number(p.beforeDown||g.down||1),oldTo=p.beforeToGo??g.toGo;const goal=String(oldTo).toLowerCase()==='goal';const need=goal?Infinity:Number(oldTo||15);const gain=(p.type==='pass'&&!p.complete)?0:Number(p.yards||0);
 if(!goal&&gain>=need){p.firstDown=true;g.down=1;g.toGo=15;return}
 g.down=oldDown+1;if(goal)g.toGo='Goal';else g.toGo=Math.max(1,need-gain);
 if(g.down>4){g.possession=p.team==='ira'?'opp':'ira';resetSeries(g);p.turnoverOnDowns=true}
}
function rebuildSituation(p){const g=ensureGame();if(!p)return;g.down=p.beforeDown??g.down;g.toGo=p.beforeToGo??g.toGo;g.possession=p.beforePossession??g.possession;g.ballOn=p.beforeBallOn??g.ballOn}
document.getElementById('playForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),p=Object.fromEntries(fd.entries());p.tacklers=fd.getAll('tackler');p.id=uid();p.at=new Date().toISOString();p.yards=Number(p.yards||0);p.points=Number(p.points||0);const g=ensureGame();p.beforeDown=g.down;p.beforeToGo=g.toGo;p.beforePossession=g.possession;p.beforeBallOn=g.ballOn;
 if(p.type==='sack')p.yards=-Math.abs(p.yards);if(p.type==='run'){p.touchdown=p.result==='td';if(p.result==='fumble')p.turnover=true}if(p.type==='pass'){p.complete=['complete','td'].includes(p.result);p.touchdown=p.result==='td';p.interception=p.result==='int'}
 [p.runner,p.passer,p.receiver,p.scorer].filter(Boolean).forEach(id=>{state.playerUse=state.playerUse||{ira:{},opp:{}};state.playerUse[p.team]=state.playerUse[p.team]||{};state.playerUse[p.team][id]=(state.playerUse[p.team][id]||0)+1});if(p.type==='possession'){g.down=1;g.toGo=15}g.plays.push(p);if(p.touchdown){if(p.team==='ira')g.iraScore+=6;else g.oppScore+=6}if(p.type==='score'&&p.points){if(p.team==='ira')g.iraScore+=p.points;else g.oppScore+=p.points}if(p.type==='turnover'||p.interception||p.turnover)g.possession=p.team==='ira'?'opp':'ira';if(['run','pass','sack'].includes(p.type)&&!(p.touchdown||p.interception||p.turnover)){g.ballOn=moveBall(g.ballOn,p.type==='pass'&&!p.complete?0:p.yards);if(g.down===1&&distanceToGoal(g.ballOn)<15)g.toGo='Goal'}advanceSituation(p);save();document.getElementById('playDialog').close();toast('Play saved');if(p.touchdown)touchdownFlow(p.team)});
function describePlay(p){const n=p.note?` — ${p.note}`:'',def=p.team==='ira'?'opp':'ira';let tack='';if(p.tackleMode==='multiple')tack=p.tacklers?.length?` • tackle: ${p.tacklers.map(id=>playerName(def,id)).join(' + ')}`:' • group tackle';else if(p.tackleMode==='single'&&p.tacklers?.[0])tack=` • tackle: ${playerName(def,p.tacklers[0])}`;if(p.type==='run')return `${teamLabel(p.team)}: ${p.runner?playerName(p.team,p.runner):'Runner'} run ${p.yards>=0?'+':''}${p.yards} yd${p.yards===1?'':'s'}${p.touchdown?' TOUCHDOWN':''}${p.firstDown?' • 1st down':''}${p.turnover?` • FUMBLE${p.recoveredBy?' recovered by '+playerName(def,p.recoveredBy):''}`:''}${tack}${n}`;if(p.type==='pass')return `${teamLabel(p.team)}: ${p.passer?playerName(p.team,p.passer):'Pass'} ${p.complete?'to '+(p.receiver?playerName(p.team,p.receiver):'receiver')+' '+p.yards+' yds':p.interception?'INTERCEPTED'+(p.interceptedBy?' by '+playerName(def,p.interceptedBy):''):'incomplete'}${p.touchdown?' TOUCHDOWN':''}${p.firstDown?' • 1st down':''}${tack}${n}`;if(p.type==='sack')return `${teamLabel(p.team)}: sack ${p.yards} yards${tack}${n}`;if(p.type==='penalty')return `Penalty: ${p.penalty||'Penalty'} on ${teamLabel(p.penaltyOn)} for ${p.yards} yards${n}`;if(p.type==='turnover')return `${teamLabel(p.team)} turnover: ${p.turnoverType}${p.defender?' • '+playerName(def,p.defender):''}${n}`;if(p.type==='score')return `${teamLabel(p.team)} scoring play: ${p.description||p.points+' points'}${p.scorer?' by '+playerName(p.team,p.scorer):''}${n}`;if(p.type==='possession')return `${teamLabel(p.team)} begins a new possession${n}`;return p.type}
function leadersTable(players){const rows=Object.entries(players).map(([id,s])=>({id,...s})).sort((a,b)=>(b.rushYds+b.recYds+b.passYds)-(a.rushYds+a.recYds+a.passYds)).slice(0,8);if(!rows.length)return '<p class="muted">No player stats yet.</p>';return `<div class="table-wrap"><table><thead><tr><th>Player</th><th class="num">Rush</th><th class="num">Pass</th><th class="num">Rec</th><th class="num">TD</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(playerName('ira',x.id))}</td><td class="num">${x.rushAtt}-${x.rushYds}</td><td class="num">${x.passComp}/${x.passAtt}-${x.passYds}</td><td class="num">${x.rec}-${x.recYds}</td><td class="num">${x.rushTD+x.passTD+x.recTD}</td></tr>`).join('')}</tbody></table></div>`}
function defenseTable(players){const rows=Object.entries(players).map(([id,s])=>({id,...s})).filter(x=>x.tackles||x.defInt||x.fumbleRec).sort((a,b)=>(b.tackles+b.defInt*3+b.fumbleRec*2)-(a.tackles+a.defInt*3+a.fumbleRec*2));if(!rows.length)return '<p class=\"muted\">No individual defensive stats yet.</p>';return `<div class=\"table-wrap\"><table><thead><tr><th>Player</th><th class=\"num\">Tkl</th><th class=\"num\">INT</th><th class=\"num\">FR</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(playerName('ira',x.id))}</td><td class=\"num\">${x.tackles||0}</td><td class=\"num\">${x.defInt||0}</td><td class=\"num\">${x.fumbleRec||0}</td></tr>`).join('')}</tbody></table></div>`}
function broadcastNotes(st){const notes=[],g=ensureGame(),ira=st.ira;notes.push(`Ira has ${ira.rushYds+ira.passYds} total yards on ${ira.plays} recorded offensive plays${ira.plays?`, ${((ira.rushYds+ira.passYds)/ira.plays).toFixed(1)} yards per play`:''}.`);if(ira.rushYds)notes.push(`The Bulldogs have rushed for ${ira.rushYds} yards.`);if(ira.passYds)notes.push(`Ira has ${ira.passYds} yards through the air.`);const players=Object.entries(ira.players).map(([id,s])=>({id,...s}));const r=players.sort((a,b)=>b.rushYds-a.rushYds)[0];if(r?.rushYds>=50)notes.push(`${playerName('ira',r.id)} leads Ira with ${r.rushYds} rushing yards on ${r.rushAtt} carries.`);if(g.iraScore!==g.oppScore)notes.push(`Ira ${g.iraScore>g.oppScore?'leads':'trails'} ${g.iraScore}-${g.oppScore} in the ${ordinalQuarter(g.quarter)}.`);return notes}
function ordinalQuarter(q){return q===1?'1st quarter':q===2?'2nd quarter':q===3?'3rd quarter':q===4?'4th quarter':'overtime'}
function comparisonTable(st){return `<div class="table-wrap"><table><thead><tr><th>Stat</th><th class="num">Ira</th><th class="num">Opponent</th></tr></thead><tbody>${[['Score','score'],['Rushing yards','rushYds'],['Passing yards','passYds'],['Total yards','total'],['First downs','firstDowns'],['Turnovers','turnovers'],['Plays','plays']].map(([label,key])=>{const a=key==='total'?st.ira.rushYds+st.ira.passYds:st.ira[key],b=key==='total'?st.opp.rushYds+st.opp.passYds:st.opp[key];return `<tr><td>${label}</td><td class="num">${a}</td><td class="num">${b}</td></tr>`}).join('')}</tbody></table></div>`}
function renderHalftime(){const g=ensureGame(),st=calc(),notes=broadcastNotes(st);document.getElementById('halftime').innerHTML=`<div class="card hero"><div class="eyebrow">HALFTIME SHOW</div><h2>IRA ${g.iraScore} — ${g.oppScore} ${esc(g.opponent)}</h2><p class="muted" style="color:#bbb">A ready-to-read first-half stat board generated from your play entries.</p></div><div class="grid two" style="margin-top:16px"><div class="card"><h2>First-Half Team Comparison</h2>${comparisonTable(st)}</div><div class="card"><h2>Ira Leaders</h2>${leadersTable(st.ira.players)}</div><div class="card"><h2>First-Half Story</h2>${notes.map(n=>`<div class="broadcast-note">${esc(n)}</div>`).join('')}</div><div class="card"><h2>Halftime Notes</h2><textarea id="halftimeNotes" placeholder="Band notes, scores from other games, sponsor reads, second-half keys…">${esc(g.notes||'')}</textarea><button id="saveHalftimeNotes" style="margin-top:8px">Save Notes</button></div></div>`;document.getElementById('saveHalftimeNotes').onclick=()=>{g.notes=document.getElementById('halftimeNotes').value;save();toast('Halftime notes saved')}}
function renderPostgame(){const g=ensureGame(),st=calc();const next=state.schedule.find(x=>x.week>g.week&&x.opponent!=='OPEN / BYE');const winner=g.iraScore>g.oppScore?'Ira wins':g.iraScore<g.oppScore?`${g.opponent} wins`:'Tie';document.getElementById('postgame').innerHTML=`<div class="card hero"><div class="eyebrow">${g.final?'FINAL':'POSTGAME PREVIEW'}</div><h2>${winner}: IRA ${g.iraScore}, ${esc(g.opponent)} ${g.oppScore}</h2><div class="talking-controls"><button id="finalBtn">${g.final?'Reopen Game':'Mark FINAL'}</button><button class="ghost" id="copyPostBtn">Copy Postgame Summary</button></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h2>By the Numbers</h2>${comparisonTable(st)}</div><div class="card"><h2>Game Leaders</h2>${leadersTable(st.ira.players)}</div><div class="card"><h2>Postgame Read</h2><div class="post-read" id="postRead">${esc(postgameRead(g,st,next))}</div></div><div class="card"><h2>Up Next</h2>${next?`<p><strong>${esc(next.opponent)}</strong><br>${fmtDate(next.date)} • ${esc(next.time)} • ${esc(next.site)}${next.district?' • District':''}</p>`:'<p class="muted">No later regular-season game is cached.</p>'}</div></div>`;document.getElementById('finalBtn').onclick=()=>{g.final=!g.final;save();toast(g.final?'Game marked final':'Game reopened')};document.getElementById('copyPostBtn').onclick=()=>navigator.clipboard?.writeText(postgameRead(g,st,next)).then(()=>toast('Postgame summary copied'))}
function postgameRead(g,st,next){const total=st.ira.rushYds+st.ira.passYds;let s=`Final: Ira ${g.iraScore}, ${g.opponent} ${g.oppScore}. The Bulldogs finish with ${total} total yards — ${st.ira.rushYds} rushing and ${st.ira.passYds} passing — with ${st.ira.firstDowns} first downs and ${st.ira.turnovers} turnover${st.ira.turnovers===1?'':'s'}.`;const ps=Object.entries(st.ira.players).map(([id,x])=>({id,...x})).sort((a,b)=>b.rushYds-a.rushYds)[0];if(ps?.rushYds)s+=` ${playerName('ira',ps.id)} led Ira on the ground with ${ps.rushYds} yards on ${ps.rushAtt} carries.`;if(next)s+=` Ira's next scheduled game is against ${next.opponent} on ${fmtDate(next.date)} at ${next.time}.`;return s}
function renderRosters(){document.getElementById('roster').innerHTML=`<div class="grid two"><div class="card"><h2>Ira Roster</h2>${rosterEditor('ira')}</div><div class="card"><h2>Opponent Roster</h2><p class="small muted">Optional, but useful if you want opponent player statistics too.</p>${rosterEditor('opp')}</div></div>`;document.querySelectorAll('[data-addroster]').forEach(b=>b.onclick=()=>addRoster(b.dataset.addroster));document.querySelectorAll('[data-delroster]').forEach(b=>b.onclick=()=>{const [team,id]=b.dataset.delroster.split(':');state.rosters[team]=state.rosters[team].filter(p=>p.id!==id);save()})}
function rosterEditor(team){const rows=(state.rosters[team]||[]).slice().sort((a,b)=>Number(a.number)-Number(b.number)).map(p=>`<div class="roster-row"><div class="jersey">#${esc(p.number)}</div><div><strong>${esc(p.name)}</strong><div class="small muted">${esc(p.position||'')}</div></div><button class="ghost" data-delroster="${team}:${p.id}">Delete</button></div>`).join('');return `<div class="form-grid" style="grid-template-columns:90px 1fr 130px"><label>#<input id="${team}Num" inputmode="numeric"></label><label>Name<input id="${team}Name" placeholder="First Last"></label><label>Position<input id="${team}Pos" placeholder="RB/QB/E"></label></div><button data-addroster="${team}" style="margin:10px 0 14px">Add Player</button><div class="roster-list">${rows||'<p class="muted">No players added yet.</p>'}</div>`}
function addRoster(team){const num=document.getElementById(team+'Num').value.trim(),name=document.getElementById(team+'Name').value.trim(),position=document.getElementById(team+'Pos').value.trim();if(!num||!name){toast('Enter jersey number and name');return}state.rosters[team].push({id:uid(),number:num,name,position});save();toast('Player added')}

// Navigation & settings
document.querySelectorAll('.tabs button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===btn.dataset.view));renderAll()});
document.getElementById('settingsBtn').onclick=()=>{document.getElementById('syncUrlInput').value=state.settings.syncUrl||'';document.getElementById('publishKeyInput').value=state.settings.publishKey||'';document.getElementById('listenUrlInput').value=state.settings.listenUrl||'';document.getElementById('settingsDialog').showModal()};document.getElementById('saveSettingsBtn').onclick=()=>{state.settings.syncUrl=document.getElementById('syncUrlInput').value.trim();state.settings.publishKey=document.getElementById('publishKeyInput').value.trim();state.settings.listenUrl=document.getElementById('listenUrlInput').value.trim();save();toast('Settings saved')};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
ensureGame();renderAll();

// --- V1.4 phone-first additions ---
function opponentColor(){
 const c=(state.opponentInfo&&state.opponentInfo.color)||'#667085';
 const orange=['#e66b16','#ff8a2b','orange'];
 return orange.includes(String(c).toLowerCase())?'#667085':c;
}
function teamPlayerTable(team,players){
 const rows=Object.entries(players||{}).map(([id,x])=>({id,...x})).sort((a,b)=>((b.rushYds+b.passYds+b.recYds+b.points)-(a.rushYds+a.passYds+a.recYds+a.points)));
 if(!rows.length)return '<p class="muted">No player stats yet.</p>';
 return `<div class="table-wrap"><table><thead><tr><th>Player</th><th>Rush</th><th>Pass</th><th>Rec</th><th>TD</th><th>Tkl</th><th>INT</th><th>FR</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(playerName(team,x.id))}</td><td>${x.rushAtt||0}-${x.rushYds||0}</td><td>${x.passComp||0}/${x.passAtt||0}-${x.passYds||0}</td><td>${x.rec||0}-${x.recYds||0}</td><td>${(x.rushTD||0)+(x.passTD||0)+(x.recTD||0)}</td><td>${x.tackles||0}</td><td>${x.defInt||0}</td><td>${x.fumbleRec||0}</td></tr>`).join('')}</tbody></table></div>`;
}
function renderStats(){
 const el=document.getElementById('stats');if(!el)return;const g=ensureGame(),st=calc();
 el.innerHTML=`<div class="card hero"><div class="eyebrow">RADIO BOOTH</div><h2>Live Stats — IRA ${g.iraScore}, ${esc(g.opponent)} ${g.oppScore}</h2></div><div class="grid two" style="margin-top:16px"><div class="card"><h2>Game Comparison</h2>${comparisonTable(st)}</div><div class="card"><h2>Ira Player Stats</h2>${teamPlayerTable('ira',st.ira.players)}</div><div class="card"><h2>${esc(g.opponent)} Player Stats</h2>${teamPlayerTable('opp',st.opp.players)}</div><div class="card"><h2>Radio Notes</h2>${broadcastNotes(st).map(x=>`<div class="broadcast-note">${esc(x)}</div>`).join('')}</div></div>`;
}
function standoutPlayers(team,players){return Object.entries(players||{}).map(([id,x])=>({id,...x,impact:(x.rushYds||0)+(x.recYds||0)+(x.passYds||0)*.55+(x.points||0)*8+(x.tackles||0)*4+(x.defInt||0)*30+(x.fumbleRec||0)*20})).sort((a,b)=>b.impact-a.impact).filter(x=>x.impact>0).slice(0,3)}
function standoutText(team,x){const bits=[];if(x.rushAtt)bits.push(`${x.rushAtt} carries, ${x.rushYds} yds`);if(x.passAtt)bits.push(`${x.passComp}/${x.passAtt}, ${x.passYds} pass yds`);if(x.rec)bits.push(`${x.rec} catches, ${x.recYds} yds`);const td=(x.rushTD||0)+(x.passTD||0)+(x.recTD||0);if(td)bits.push(`${td} TD`);if(x.tackles)bits.push(`${x.tackles} tackles`);if(x.defInt)bits.push(`${x.defInt} INT`);if(x.fumbleRec)bits.push(`${x.fumbleRec} FR`);return `<div class="broadcast-note"><strong>${esc(playerName(team,x.id))}</strong> — ${esc(bits.join(' • '))}</div>`}
function nextGameCard(next){if(!next)return '<p class="muted">No later regular-season game is cached.</p>';const pd=(state.pregameData||{})[next.week]||{};return `<h3>${esc(next.opponent)}</h3><p><strong>${fmtDate(next.date)} • ${esc(next.time)} • ${esc(next.site)}</strong>${next.district?' • District':''}</p><div class="summary-grid"><div class="summary-item"><span class="kicker">SixManFootball rank</span><strong>${next.rank?'#'+next.rank:'—'}</strong></div><div class="summary-item"><span class="kicker">Projection</span><strong>${esc(pd.projection||'Refresh when available')}</strong></div></div><h3 style="margin-top:14px">Common Opponents</h3><p class="muted">${esc(pd.commonOpponents||'Common-opponent comparisons will populate from cached SixManFootball results as the season develops.')}</p>`}
function renderPostgame(){const g=ensureGame(),st=calc(),next=state.schedule.find(x=>x.week>g.week&&x.opponent!=='OPEN / BYE'),winner=g.iraScore>g.oppScore?'Ira wins':g.iraScore<g.oppScore?`${g.opponent} wins`:'Tie',iraP=standoutPlayers('ira',st.ira.players),oppP=standoutPlayers('opp',st.opp.players);document.getElementById('postgame').innerHTML=`<div class="card hero"><div class="eyebrow">${g.final?'FINAL':'POSTGAME PREVIEW'}</div><h2>${winner}: IRA ${g.iraScore}, ${esc(g.opponent)} ${g.oppScore}</h2><div class="talking-controls"><button id="finalBtn">${g.final?'Reopen Game':'🏁 FINALIZE GAME'}</button>${g.final&&next?'<button id="nextGameBtn">🏈 START NEXT GAME</button>':''}<button class="ghost" id="copyPostBtn">Copy Postgame Summary</button></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h2>By the Numbers</h2>${comparisonTable(st)}</div><div class="card"><h2>Players of the Game — Suggestions</h2><h3>Ira</h3>${iraP.map(x=>standoutText('ira',x)).join('')||'<p class="muted">No stats yet.</p>'}<h3 style="margin-top:14px">${esc(g.opponent)}</h3>${oppP.map(x=>standoutText('opp',x)).join('')||'<p class="muted">No stats yet.</p>'}</div><div class="card"><h2>Postgame Read</h2><div class="post-read" id="postRead">${esc(postgameRead(g,st,next))}</div></div><div class="card"><div class="eyebrow">NEXT GAME PREVIEW</div>${nextGameCard(next)}</div></div>`;document.getElementById('finalBtn').onclick=()=>{g.final=!g.final;save();toast(g.final?'Game finalized and preserved':'Game reopened')};const n=document.getElementById('nextGameBtn');if(n)n.onclick=()=>{state.selectedWeek=next.week;ensureGame();save();document.querySelector('[data-view=pregame]').click();toast('Next game ready')};document.getElementById('copyPostBtn').onclick=()=>navigator.clipboard?.writeText(postgameRead(g,st,next)).then(()=>toast('Postgame summary copied'))}
function renderRosters(){document.getElementById('roster').innerHTML=`<div class="grid two"><div class="card"><h2>Ira Roster</h2>${rosterEditor('ira')}</div><div class="card"><h2>Opponent Roster</h2><p class="small muted">Used for opponent stats too.</p>${rosterEditor('opp')}</div></div>`;document.querySelectorAll('[data-addroster]').forEach(b=>b.onclick=()=>addRoster(b.dataset.addroster));document.querySelectorAll('[data-delroster]').forEach(b=>b.onclick=()=>{const [team,id]=b.dataset.delroster.split(':');state.rosters[team]=state.rosters[team].filter(p=>p.id!==id);save()});document.querySelectorAll('[data-editroster]').forEach(b=>b.onclick=()=>{const [team,id]=b.dataset.editroster.split(':'),p=state.rosters[team].find(x=>x.id===id);if(!p)return;const num=prompt('Jersey number',p.number);if(num===null)return;const name=prompt('Player name',p.name);if(name===null)return;const pos=prompt('Position',p.position||'');if(pos===null)return;p.number=num.trim();p.name=name.trim();p.position=pos.trim();save();toast('Player updated')})}
function rosterEditor(team){const rows=(state.rosters[team]||[]).slice().sort((a,b)=>Number(a.number)-Number(b.number)).map(p=>`<div class="roster-row"><div class="jersey">#${esc(p.number)}</div><div><strong>${esc(p.name)}</strong><div class="small muted">${esc(p.position||'')}</div></div><div class="player-actions"><button class="ghost" data-editroster="${team}:${p.id}">Edit</button><button class="ghost" data-delroster="${team}:${p.id}">Delete</button></div></div>`).join('');return `<div class="form-grid" style="grid-template-columns:90px 1fr 130px"><label>#<input id="${team}Num" inputmode="numeric"></label><label>Name<input id="${team}Name" placeholder="First Last"></label><label>Position<input id="${team}Pos" placeholder="RB/QB/E"></label></div><button data-addroster="${team}" style="margin:10px 0 14px">Add Player</button><div class="roster-list">${rows||'<p class="muted">No players added yet.</p>'}</div>`}
function ballParts(v){const m=String(v||'Own 20').match(/(Own|Opp)\s*(\d+)/i);return {side:m&&/^opp/i.test(m[1])?'Opp':'Own',yard:m?Number(m[2]):20}}
function distanceToGoal(v){const b=ballParts(v);return b.side==='Opp'?b.yard:80-b.yard}
function moveBall(v,gain){let b=ballParts(v),pos=b.side==='Own'?b.yard:80-b.yard;pos=Math.max(1,Math.min(79,pos+Number(gain||0)));return pos<=40?`Own ${pos}`:`Opp ${80-pos}`}
function touchdownFlow(team){setTimeout(()=>{
 const g=ensureGame();const choice=prompt('Touchdown conversion: enter 1 for run/pass PAT, 2 for kick PAT, or 0 for no good / skip','0');if(choice===null)return;const pts=['0','1','2'].includes(choice)?Number(choice):0;if(pts){if(team==='ira')g.iraScore+=pts;else g.oppScore+=pts;g.plays.push({id:uid(),at:new Date().toISOString(),type:'score',team,points:pts,description:pts===2?'Kick PAT good':'Run/Pass PAT good'})}
 const onside=confirm('Onside kick?\nOK = Onside kick\nCancel = Normal kick');let receiver=team==='ira'?'opp':'ira';if(onside){const kickingRecovered=confirm('Did the KICKING team recover the onside kick?');receiver=kickingRecovered?team:(team==='ira'?'opp':'ira')}
 g.possession=receiver;g.down=1;g.toGo=15;const spot=prompt(`Starting field position for ${teamLabel(receiver)} (example: Own 22 or Opp 10)`,'Own 20');if(spot){const b=ballParts(spot);g.ballOn=`${b.side} ${b.yard}`;if(distanceToGoal(g.ballOn)<15)g.toGo='Goal'}save();toast('Next drive ready');
 },120)}

// ===== V1.4.1 GAME-DAY HOTFIX OVERRIDES =====
const V141=true;
function teamLabel(t){const g=ensureGame();return t==='ira'?'Ira Bulldogs':(g.opponent||'Opponent')}
function teamShort(t){return t==='ira'?'Ira':(ensureGame().opponent||'Opponent')}
function normalizeGoal(g){if(!g)return;if(distanceToGoal(g.ballOn)<15)g.toGo='Goal';else if(String(g.toGo).toLowerCase()==='goal')g.toGo=15}
function seriesReset(g){g.down=1;g.toGo=distanceToGoal(g.ballOn)<15?'Goal':15}
function yardSelect(name,value=20){return `<select name="${name}" class="yard-select">${Array.from({length:40},(_,i)=>i+1).map(n=>`<option value="${n}" ${Number(value)===n?'selected':''}>${n}</option>`).join('')}</select>`}
function quickYards(vals=[-15,-10,-5,0,5,10,15]){return `<div class="quick-yards">${vals.map(x=>`<button type="button" data-yard="${x}">${x>0?'+':''}${x}</button>`).join('')}</div>`}
function defenderPicks(defTeam,label='Tackled By — optional'){const players=(state.rosters[defTeam]||[]).slice().sort((a,b)=>Number(a.number)-Number(b.number));return `<div class="defense-box"><div class="kicker">${esc(teamLabel(defTeam).toUpperCase())} DEFENSE</div><div class="field-label">${label}</div><div class="tackler-picks">${players.map(p=>`<label class="check-pill"><input type="checkbox" name="tackler" value="${p.id}"> #${esc(p.number)} ${esc(p.name)}</label>`).join('')||'<span class="muted small">No defenders on this roster yet. Leave blank to skip individual credit.</span>'}</div><div class="muted small">No player = skip • 1 player = full credit • 2+ = shared/group credit</div></div>`}
function recoveryBlock(offTeam){const defTeam=offTeam==='ira'?'opp':'ira';return `<div class="defense-box recovery-block"><div class="kicker">FUMBLE RECOVERY</div><input type="hidden" name="recoveryTeam" value="${defTeam}"><div class="result-buttons recovery-team-buttons"><button type="button" data-recovery-team="${offTeam}">${esc(teamShort(offTeam))}</button><button type="button" data-recovery-team="${defTeam}" class="selected">${esc(teamShort(defTeam))}</button></div><label>Who recovered? <select name="recoveredBy">${playerOptions(defTeam)}</select></label><label>Return / advance after recovery <select name="returnYards">${Array.from({length:81},(_,i)=>i-40).map(n=>`<option value="${n}" ${n===0?'selected':''}>${n>0?'+':''}${n}</option>`).join('')}</select></label></div>`}
function passResultExtras(result,team,defTeam){if(result==='int')return `<div class="special-result"><div class="form-grid two-col"><label>Pass distance to interception<select name="yards">${Array.from({length:61},(_,i)=>i-20).map(n=>`<option value="${n}" ${n===10?'selected':''}>${n>0?'+':''}${n}</option>`).join('')}</select></label><label>INT return yards<select name="returnYards">${Array.from({length:81},(_,i)=>i-40).map(n=>`<option value="${n}" ${n===0?'selected':''}>${n>0?'+':''}${n}</option>`).join('')}</select></label></div><label>Intercepted by<select name="interceptedBy">${playerOptions(defTeam)}</select></label></div>`;
 if(result==='sack')return `<div class="special-result"><div class="kicker">YARDS LOST</div>${quickYards([3,5,7,10])}<input type="hidden" class="yards-input" name="yards" value="5">${defenderPicks(defTeam,'Sack made by — optional')}</div>`;
 if(result==='fumble')return `<div class="special-result"><label>Yards before fumble<select name="yards">${Array.from({length:61},(_,i)=>i-20).map(n=>`<option value="${n}" ${n===5?'selected':''}>${n>0?'+':''}${n}</option>`).join('')}</select></label>${recoveryBlock(team)}</div>`;
 return ''}

function openPlay(type){const g=ensureGame(),team=g.possession,defTeam=team==='ira'?'opp':'ira',d=document.getElementById('playDialog'),fields=document.getElementById('playFormFields');
 const titles={run:'Run',pass:'Pass',penalty:'Penalty',turnover:'Other Turnover',score:'Other Score',possession:'New Drive'};document.getElementById('playDialogTitle').textContent=titles[type]||type;document.getElementById('playDialogEyebrow').textContent=`${teamLabel(team).toUpperCase()} OFFENSE`;
 let html=`<input type="hidden" name="type" value="${type}"><input type="hidden" name="team" value="${team}">`;
 if(type==='run')html+=`<div class="form-grid"><label>Ball carrier<select name="runner">${playerOptions(team)}</select></label><input type="hidden" name="result" value="normal"><div><span class="kicker">RESULT</span><div class="result-buttons"><button type="button" data-result="normal" class="selected">NORMAL</button><button type="button" data-result="td">TD</button><button type="button" data-result="fumble">FUMBLE</button></div></div></div><div class="yard-section"><div class="kicker">YARDS GAINED / LOST</div>${quickYards([-10,-5,0,3,5,10,15,20])}<label class="manual-yard">Other<select class="yards-input" name="yards">${Array.from({length:81},(_,i)=>i-30).map(n=>`<option value="${n}" ${n===0?'selected':''}>${n>0?'+':''}${n}</option>`).join('')}</select></label></div><div id="runResultExtra"></div>${defenderPicks(defTeam)}`;
 if(type==='pass')html+=`<div class="form-grid"><label>Passer<select name="passer">${playerOptions(team)}</select></label><label>Receiver<select name="receiver">${playerOptions(team)}</select></label></div><input type="hidden" name="result" value="complete"><div><span class="kicker">RESULT</span><div class="result-buttons pass-results"><button type="button" data-result="complete" class="selected">COMPLETE</button><button type="button" data-result="incomplete">INCOMPLETE</button><button type="button" data-result="int">INTERCEPTED</button><button type="button" data-result="sack">SACK</button><button type="button" data-result="fumble">FUMBLE</button><button type="button" data-result="td">TD</button></div></div><div id="normalPassYards"><div class="kicker">YARDS</div>${quickYards([-5,0,5,10,15,20,30])}<label>Other<select class="yards-input" name="yards">${Array.from({length:81},(_,i)=>i-20).map(n=>`<option value="${n}" ${n===0?'selected':''}>${n>0?'+':''}${n}</option>`).join('')}</select></label></div><div id="passResultExtra"></div><div id="passTackles">${defenderPicks(defTeam)}</div>`;
 if(type==='penalty')html+=`<div class="form-grid"><label>Penalty<input name="penalty" placeholder="Holding, offsides…"></label><label>Player / number (optional)<input name="penaltyPlayer" placeholder="#12"></label><label>Status<select name="penaltyStatus"><option value="accepted">Accepted</option><option value="declined">Declined</option><option value="offsetting">Offsetting</option></select></label></div><div class="kicker">YARDAGE — RELATIVE TO OFFENSE</div>${quickYards([-15,-10,-5,0,5,10,15])}<input type="hidden" class="yards-input" name="yards" value="0"><div class="result-buttons"><button type="button" data-offsetting>OFFSETTING PENALTIES</button></div><p class="muted small">Negative hurts the offense; positive helps the offense. Offsetting/declined leaves the situation unchanged.</p>`;
 if(type==='turnover')html+=`<label>What happened?<input name="turnoverType" placeholder="Bad snap, loose ball, unusual turnover…"></label>${defenderPicks(defTeam,'Defender credit — optional')}<p class="muted small">Use this only for unusual turnovers. Normal interceptions, fumbles and turnover on downs are handled automatically.</p>`;
 if(type==='score')html+=`<div class="form-grid"><label>Scorer<select name="scorer">${playerOptions(team)}</select></label><label>Score type<select name="scoreType"><option value="4">Field Goal • 4</option><option value="2">Safety • 2</option><option value="manual">Other / Manual</option></select></label><label>Manual points<input name="manualPoints" type="number" inputmode="numeric" value="0"></label></div>`;
 if(type==='possession'){const bp=ballParts(g.ballOn);html+=`<p class="muted">Emergency catch-up tool. Set who has the ball and where, then save a clean new series.</p><div class="result-buttons"><button type="button" data-drive-team="ira" class="${team==='ira'?'selected':''}">IRA BULLDOGS</button><button type="button" data-drive-team="opp" class="${team==='opp'?'selected':''}">${esc(g.opponent.toUpperCase())}</button></div><input type="hidden" name="driveTeam" value="${team}"><div class="form-grid two-col"><label>Ball side<select name="ballSide"><option ${bp.side==='Own'?'selected':''}>Own</option><option ${bp.side==='Opp'?'selected':''}>Opp</option></select></label><label>Yard line${yardSelect('ballYard',bp.yard)}</label></div>`}
 html+=`<label style="display:grid;gap:6px;margin-top:12px">Radio note (optional)<input name="note" placeholder="Great block, injury timeout, catch-up note…"></label>`;fields.innerHTML=html;
 const updateResult=()=>{const r=fields.querySelector('[name=result]')?.value;if(type==='run'){const ex=fields.querySelector('#runResultExtra');if(ex)ex.innerHTML=r==='fumble'?recoveryBlock(team):''}if(type==='pass'){const ex=fields.querySelector('#passResultExtra'),normal=fields.querySelector('#normalPassYards'),t=fields.querySelector('#passTackles');if(ex)ex.innerHTML=passResultExtras(r,team,defTeam);if(normal)normal.style.display=['int','sack','fumble','incomplete'].includes(r)?'none':'';if(t)t.style.display=['complete','td'].includes(r)?'':'none';bindPlayDynamic(fields,team,defTeam)}};
 fields.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{fields.querySelector('[name=result]').value=b.dataset.result;fields.querySelectorAll('[data-result]').forEach(x=>x.classList.toggle('selected',x===b));updateResult()});bindPlayDynamic(fields,team,defTeam);d.showModal();
}
function bindPlayDynamic(fields,team,defTeam){fields.querySelectorAll('[data-yard]').forEach(b=>b.onclick=()=>{const scope=b.closest('.yard-section,.special-result,#normalPassYards,#playFormFields')||fields;const input=scope.querySelector('.yards-input')||fields.querySelector('.yards-input');if(input)input.value=b.dataset.yard});fields.querySelectorAll('[data-recovery-team]').forEach(b=>b.onclick=()=>{const block=b.closest('.recovery-block'),t=b.dataset.recoveryTeam;block.querySelector('[name=recoveryTeam]').value=t;block.querySelectorAll('[data-recovery-team]').forEach(x=>x.classList.toggle('selected',x===b));block.querySelector('[name=recoveredBy]').innerHTML=playerOptions(t)});fields.querySelectorAll('[data-drive-team]').forEach(b=>b.onclick=()=>{fields.querySelector('[name=driveTeam]').value=b.dataset.driveTeam;fields.querySelectorAll('[data-drive-team]').forEach(x=>x.classList.toggle('selected',x===b))});const off=fields.querySelector('[data-offsetting]');if(off)off.onclick=()=>{fields.querySelector('[name=penaltyStatus]').value='offsetting';fields.querySelector('.yards-input').value=0;off.classList.add('selected')}}

function applyPlayForm(fd){const p=Object.fromEntries(fd.entries()),g=ensureGame();p.tacklers=fd.getAll('tackler');p.id=uid();p.at=new Date().toISOString();p.yards=Number(p.yards||0);p.returnYards=Number(p.returnYards||0);p.beforeDown=g.down;p.beforeToGo=g.toGo;p.beforePossession=g.possession;p.beforeBallOn=g.ballOn;p.beforeIraScore=g.iraScore;p.beforeOppScore=g.oppScore;
 if(p.type==='pass'){p.complete=['complete','td','fumble'].includes(p.result);p.touchdown=p.result==='td';p.interception=p.result==='int';p.sack=p.result==='sack';if(p.sack)p.yards=-Math.abs(p.yards)}
 if(p.type==='run'){p.touchdown=p.result==='td';p.fumble=p.result==='fumble'}
 if(p.type==='penalty'&&p.penaltyStatus!=='accepted')p.yards=0;
 if(p.type==='score'){p.points=p.scoreType==='manual'?Number(p.manualPoints||0):Number(p.scoreType||0)}
 if(p.type==='turnover')p.turnover=true;
 if((p.type==='run'&&p.fumble)||(p.type==='pass'&&p.result==='fumble'))p.turnover=p.recoveryTeam&&p.recoveryTeam!==p.team;
 // Scoring boundary must be checked BEFORE moveBall clamps the field to Own/Opp 1.
 // A normal run or completed pass that reaches/crosses the goal line is a TD even if the broadcaster did not tap TD.
 const goalDistanceBefore=distanceToGoal(g.ballOn);
 const autoGoalLineTD=(p.type==='run'&&!p.fumble&&p.yards>=goalDistanceBefore)||(p.type==='pass'&&p.complete&&!p.interception&&!p.sack&&p.result!=='fumble'&&p.yards>=goalDistanceBefore);
 if(autoGoalLineTD)p.touchdown=true;
 [p.runner,p.passer,p.receiver,p.scorer].filter(Boolean).forEach(id=>{state.playerUse=state.playerUse||{ira:{},opp:{}};state.playerUse[p.team]=state.playerUse[p.team]||{};state.playerUse[p.team][id]=(state.playerUse[p.team][id]||0)+1});
 if(p.type==='possession'){g.possession=p.driveTeam||g.possession;g.ballOn=`${p.ballSide||'Own'} ${Number(p.ballYard||20)}`;seriesReset(g);g.plays.push(p);save();return {p,td:false}}
 g.plays.push(p);
 if(p.touchdown){if(p.team==='ira')g.iraScore+=6;else g.oppScore+=6;return {p,td:true}}
 if(p.type==='score'&&p.points){if(p.team==='ira')g.iraScore+=p.points;else g.oppScore+=p.points;save();return {p,td:false}}
 if(p.type==='penalty'){if(p.penaltyStatus==='accepted'){g.ballOn=moveBall(g.ballOn,p.yards);const oldGoal=String(g.toGo).toLowerCase()==='goal';if(!oldGoal)g.toGo=Math.max(1,Number(g.toGo||15)-p.yards);normalizeGoal(g)}save();return {p,td:false}}
 if(p.type==='turnover'){g.possession=p.team==='ira'?'opp':'ira';seriesReset(g);save();return {p,td:false}}
 const gain=(p.type==='pass'&&!p.complete&&!p.interception&&!p.sack)?0:p.yards;
 if(p.interception){g.ballOn=moveBall(g.ballOn,p.yards);g.possession=p.team==='ira'?'opp':'ira';g.ballOn=moveBall(g.ballOn,p.returnYards);seriesReset(g);save();return {p,td:false}}
 if((p.type==='run'&&p.fumble)||(p.type==='pass'&&p.result==='fumble')){g.ballOn=moveBall(g.ballOn,p.yards);if(p.recoveryTeam)g.possession=p.recoveryTeam;g.ballOn=moveBall(g.ballOn,p.recoveryTeam===p.team?p.returnYards:-p.returnYards);seriesReset(g);save();return {p,td:false}}
 if(['run','pass'].includes(p.type)||p.sack){g.ballOn=moveBall(g.ballOn,gain);const oldDown=Number(p.beforeDown||1),oldTo=p.beforeToGo,goal=String(oldTo).toLowerCase()==='goal',need=goal?Infinity:Number(oldTo||15);if(!goal&&gain>=need){p.firstDown=true;g.down=1;g.toGo=15}else{g.down=oldDown+1;g.toGo=goal?'Goal':Math.max(1,need-gain)}if(g.down>4){g.possession=p.team==='ira'?'opp':'ira';p.turnoverOnDowns=true;seriesReset(g)}normalizeGoal(g)}save();return {p,td:false}
}
// Intercept the legacy submit handler before it runs.
document.getElementById('playForm').addEventListener('submit',e=>{e.preventDefault();e.stopImmediatePropagation();const result=applyPlayForm(new FormData(e.target));document.getElementById('playDialog').close();toast('Play saved');if(result.td)touchdownFlow(result.p.team)},true);

function calc(){const g=ensureGame(),teams={ira:{...blankTeamStats(),players:{}},opp:{...blankTeamStats(),players:{}}};const pstat=(t,id)=>{if(!id)return null;if(!teams[t].players[id])teams[t].players[id]={rushAtt:0,rushYds:0,rushTD:0,passAtt:0,passComp:0,passYds:0,passTD:0,int:0,rec:0,recYds:0,recTD:0,points:0,tackles:0,sacks:0,defInt:0,fumbleRec:0,intReturnYds:0,fumbleReturnYds:0};return teams[t].players[id]};
 for(const p of g.plays){const t=teams[p.team],def=p.team==='ira'?'opp':'ira';if(!t)continue;if(['run','pass'].includes(p.type)||p.sack)t.plays++;
  if(p.type==='run'){t.rushYds+=Number(p.yards||0);const r=pstat(p.team,p.runner);if(r){r.rushAtt++;r.rushYds+=Number(p.yards||0);if(p.touchdown){r.rushTD++;r.points+=6}}if(p.firstDown)t.firstDowns++;if(p.fumble&&p.recoveryTeam!==p.team)t.turnovers++}
  if(p.type==='pass'){const q=pstat(p.team,p.passer);if(q)q.passAtt++;if(p.complete){if(q){q.passComp++;q.passYds+=Number(p.yards||0)}t.passYds+=Number(p.yards||0);const r=pstat(p.team,p.receiver);if(r){r.rec++;r.recYds+=Number(p.yards||0);if(p.touchdown){r.recTD++;r.points+=6}}if(p.touchdown&&q)q.passTD++;if(p.firstDown)t.firstDowns++}if(p.interception){if(q)q.int++;t.turnovers++;const d=pstat(def,p.interceptedBy);if(d){d.defInt++;d.intReturnYds+=Number(p.returnYards||0)}}if(p.result==='fumble'&&p.recoveryTeam!==p.team)t.turnovers++;if(p.sack||p.result==='sack')t.passYds+=Number(p.yards||0)}
  if(p.type==='turnover')t.turnovers++;
  if(p.tacklers?.length){const credit=p.sack||p.result==='sack'?(1/p.tacklers.length):1;p.tacklers.forEach(id=>{const d=pstat(def,id);if(d){d.tackles+=p.tacklers.length>1?0.5:1;if(p.sack||p.result==='sack')d.sacks+=credit}})}
  if(((p.type==='run'&&p.fumble)||(p.type==='pass'&&p.result==='fumble'))&&p.recoveredBy){const rt=p.recoveryTeam||def,d=pstat(rt,p.recoveredBy);if(d){d.fumbleRec++;d.fumbleReturnYds+=Number(p.returnYards||0)}}
  if(p.type==='score'){const s=pstat(p.team,p.scorer);if(s)s.points+=Number(p.points||0)}
 }
 teams.ira.score=g.iraScore;teams.opp.score=g.oppScore;return teams}

function describePlay(p){const def=p.team==='ira'?'opp':'ira',note=p.note?` — ${p.note}`:'',tack=p.tacklers?.length?` • tackle: ${p.tacklers.map(id=>playerName(def,id)).join(' + ')}`:'';
 if(p.type==='run')return `${teamShort(p.team)}: ${p.runner?playerName(p.team,p.runner):'Runner'} ${p.touchdown?'TOUCHDOWN ':''}run ${p.yards>=0?'+':''}${p.yards} yds${p.fumble?` • FUMBLE after ${p.yards} yds${p.recoveryTeam?' • '+teamShort(p.recoveryTeam)+' recovers':''}${p.returnYards?` • advance/return ${p.returnYards} yds`:''}`:''}${p.firstDown?' • 1st down':''}${tack}${note}`;
 if(p.type==='pass'){if(p.interception)return `${teamShort(p.team)}: pass INTERCEPTED ${p.yards} yds downfield${p.interceptedBy?' by '+playerName(def,p.interceptedBy):''}${p.returnYards?` • return ${p.returnYards} yds`:''}${note}`;if(p.sack||p.result==='sack')return `${teamShort(p.team)}: SACK for ${Math.abs(p.yards)} yd loss${tack}${note}`;if(p.result==='fumble')return `${teamShort(p.team)}: ${p.passer?playerName(p.team,p.passer):'Pass'} to ${p.receiver?playerName(p.team,p.receiver):'receiver'} for ${p.yards} yds • FUMBLE${p.recoveryTeam?' • '+teamShort(p.recoveryTeam)+' recovers':''}${p.returnYards?` • advance/return ${p.returnYards} yds`:''}${note}`;return `${teamShort(p.team)}: ${p.complete?`${p.passer?playerName(p.team,p.passer):'Pass'} to ${p.receiver?playerName(p.team,p.receiver):'receiver'} for ${p.yards} yds`:'incomplete pass'}${p.touchdown?' • TOUCHDOWN':''}${p.firstDown?' • 1st down':''}${tack}${note}`}
 if(p.type==='penalty')return `Penalty: ${p.penalty||'Penalty'}${p.penaltyPlayer?' '+p.penaltyPlayer:''} • ${p.penaltyStatus||'accepted'}${p.penaltyStatus==='accepted'?` • ${p.yards>0?'+':''}${p.yards} yds vs offense`:''}${note}`;
 if(p.type==='turnover')return `${teamShort(p.team)} other turnover: ${p.turnoverType||'unusual turnover'}${tack}${note}`;if(p.type==='score')return `${teamShort(p.team)}: ${p.description||'Other score'} +${p.points}${note}`;if(p.type==='possession')return `New drive: ${teamShort(p.driveTeam||p.team)} at ${p.ballSide||''} ${p.ballYard||''}${note}`;return p.type}

function clockControls(prefix,clock){const m=String(clock||'10:00').match(/(\d{1,2}):(\d{2})/),mm=m?Number(m[1]):10,ss=m?Number(m[2]):0;return `<div class="clock-picker"><label>Minutes<select id="${prefix}Min">${Array.from({length:11},(_,i)=>i).map(n=>`<option ${n===mm?'selected':''}>${n}</option>`).join('')}</select></label><label>Seconds<select id="${prefix}Sec">${Array.from({length:60},(_,i)=>i).map(n=>`<option value="${n}" ${n===ss?'selected':''}>${String(n).padStart(2,'0')}</option>`).join('')}</select></label></div><details><summary>Exact manual clock</summary><input id="${prefix}Manual" inputmode="numeric" placeholder="5:42" value="${esc(clock||'')}"></details>`}
function selectedClock(prefix){const manual=document.getElementById(prefix+'Manual')?.value.trim(),min=document.getElementById(prefix+'Min')?.value,sec=document.getElementById(prefix+'Sec')?.value;if(document.activeElement?.id===prefix+'Manual'&&/^\d{1,2}:\d{2}$/.test(manual))return manual;return `${Number(min||0)}:${String(Number(sec||0)).padStart(2,'0')}`}
function openClockDialog(){const g=ensureGame(),d=document.getElementById('clockDialog');document.getElementById('clockPickerMount').innerHTML=clockControls('clockPick',g.clock);d.showModal()}
function openScoreDialog(team){scoreEditTeam=team==='opp'?'opp':'ira';const g=ensureGame(),name=teamLabel(scoreEditTeam),current=scoreEditTeam==='ira'?g.iraScore:g.oppScore;document.getElementById('scoreDialogTitle').textContent=name+' Score / Clock';document.getElementById('exactScoreInput').value=current;document.getElementById('scoreClockMount').innerHTML=clockControls('scoreClock',g.clock);document.getElementById('scoreDialog').showModal()}
function commitClock(prefix){const g=ensureGame();g.clock=selectedClock(prefix);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));schedulePublish()}
function updateQuickScore(delta){const g=ensureGame(),key=scoreEditTeam==='ira'?'iraScore':'oppScore';g[key]=Math.max(0,Number(g[key]||0)+Number(delta||0));commitClock('scoreClock');save();document.getElementById('scoreDialog').close();toast(`${teamShort(scoreEditTeam)} ${g[key]} • ${g.clock}`)}
document.getElementById('setExactScoreBtn').onclick=()=>{const g=ensureGame(),key=scoreEditTeam==='ira'?'iraScore':'oppScore';g[key]=Math.max(0,Number(document.getElementById('exactScoreInput').value||0));commitClock('scoreClock');save();document.getElementById('scoreDialog').close();toast('Score and clock corrected')};

function renderLive(){const g=ensureGame(),st=calc(),bp=ballParts(g.ballOn);normalizeGoal(g);
 document.getElementById('live').innerHTML=`<div class="desktop-console">
 <section class="console-score card hero"><div class="eyebrow">LIVE GAME • WEEK ${g.week} • DESKTOP RADIO CONSOLE</div><div class="scoreboard"><button type="button" class="score-team" data-score-team="ira"><div class="team-name">IRA BULLDOGS</div><div class="team-score">${g.iraScore}</div><div class="score-tap-hint">CLICK TO EDIT SCORE / CLOCK</div></button><div class="score-center"><div class="console-clock">${esc(g.clock)}</div><div class="console-quarter">${g.final?'FINAL':`Q${g.quarter}`}</div><button type="button" class="ghost compact" id="clockBtn">Edit Clock</button></div><button type="button" class="score-team" data-score-team="opp"><div class="team-name">${esc(g.opponent)}</div><div class="team-score">${g.oppScore}</div><div class="score-tap-hint">CLICK TO EDIT SCORE / CLOCK</div></button></div></section>
 <section class="console-situation card offense-card ${g.possession==='ira'?'ira-offense':'opp-offense'}" style="--opp-color:${opponentColor()}"><div class="offense-banner">${g.possession==='ira'?'IRA BULLDOGS BALL':esc(g.opponent.toUpperCase())+' BALL'}</div><div class="possession"><button data-pos="ira" class="${g.possession==='ira'?'active':''}">IRA BALL</button><button data-pos="opp" class="${g.possession==='opp'?'active':''}">${esc(g.opponent.toUpperCase())} BALL</button></div><div class="game-meta desktop-meta"><label>Quarter<select id="quarterSel">${[1,2,3,4,5].map(q=>`<option ${g.quarter===q?'selected':''}>${q}</option>`).join('')}</select></label><label>Down<select id="downSel">${[1,2,3,4].map(x=>`<option ${g.down===x?'selected':''}>${x}</option>`).join('')}</select></label><label>To Go<select id="toGoInput">${toGoOptions(g.toGo)}</select></label><label>Ball Side<select id="ballSideInput"><option ${bp.side==='Own'?'selected':''}>Own</option><option ${bp.side==='Opp'?'selected':''}>Opp</option></select></label><label>Yard Line<select id="ballYardInput">${Array.from({length:40},(_,i)=>i+1).map(n=>`<option ${bp.yard===n?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="situation-readout"><strong>${g.down}${g.down===1?'st':g.down===2?'nd':g.down===3?'rd':'th'} &amp; ${String(g.toGo).toLowerCase()==='goal'?'Goal':g.toGo}</strong><span>${esc(g.ballOn)}</span></div><div class="live-controls desktop-actions"><button class="run" data-play="run">RUN <small>optional stats</small></button><button class="pass" data-play="pass">PASS <small>optional stats</small></button><button class="penalty" data-play="penalty">PENALTY</button><button data-play="turnover">OTHER TURNOVER</button><button class="score" data-play="score">OTHER SCORE</button><button data-play="possession">NEW DRIVE / CATCH UP</button><button class="dark" id="undoBtn">UNDO LAST</button></div></section>
 <section class="console-notes card"><div class="inline console-heading"><div><div class="eyebrow">RADIO BOOTH</div><h2>My Notes</h2></div><span id="notesSaved" class="muted small">Auto-saves</span></div><textarea id="radioNotes" class="radio-notes-area" placeholder="Injuries, trends, sponsor reminders, things to mention on air…">${esc(g.notes||'')}</textarea><div class="public-update-box"><div class="inline console-heading"><div><div class="eyebrow">WEBSITE</div><h3>Latest Public Update</h3></div><button type="button" id="clearPublicUpdate" class="ghost compact">Clear</button></div><textarea id="publicUpdate" placeholder="Optional: Ira scores on a long run. Halftime: Ira leads 28-14.">${esc(g.publicUpdate||'')}</textarea><div class="muted small">Optional — score and game status remain useful even with no play stats.</div></div></section>
 <section class="console-plays card"><div class="inline console-heading"><div><h2>Optional Play Log</h2><div class="small muted">Use it when you can. Ignore it when broadcasting gets busy.</div></div><button class="dark compact" id="loadCloudBtn">☁ Load Cloud</button></div><div class="play-log">${[...g.plays].reverse().map((p,i)=>`<div class="play-row"><div class="seq">#${g.plays.length-i}</div><div>${esc(describePlay(p))}</div><button class="ghost" data-delplay="${p.id}">Delete</button></div>`).join('')||'<p class="muted">No plays entered — that is fine. Scoreboard and notes work independently.</p>'}</div></section>
 <section class="console-mini-stats card"><h2>Recorded Stats <span class="small muted">— only the plays you chose to enter</span></h2><div class="stat-strip desktop-stat-strip"><div class="stat-box"><strong>${st.ira.rushYds}</strong><span>Rush yds</span></div><div class="stat-box"><strong>${st.ira.passYds}</strong><span>Pass yds</span></div><div class="stat-box"><strong>${st.ira.rushYds+st.ira.passYds}</strong><span>Total yds</span></div><div class="stat-box"><strong>${st.ira.firstDowns}</strong><span>1st downs</span></div><div class="stat-box"><strong>${st.ira.turnovers}</strong><span>Turnovers</span></div><div class="stat-box"><strong>${st.ira.plays}</strong><span>Plays entered</span></div></div></section></div>`;
 document.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{g.possession=b.dataset.pos;normalizeGoal(g);save()});document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>openPlay(b.dataset.play));document.querySelectorAll('[data-score-team]').forEach(b=>b.onclick=()=>openScoreDialog(b.dataset.scoreTeam));document.getElementById('clockBtn').onclick=openClockDialog;document.getElementById('loadCloudBtn').onclick=loadCloudGame;
 const cs=(id,key,num=false)=>{const e=document.getElementById(id);if(e)e.onchange=()=>{g[key]=num?Number(e.value):e.value;if(key==='down'||key==='toGo')normalizeGoal(g);save()}};cs('quarterSel','quarter',true);cs('downSel','down',true);cs('toGoInput','toGo');
 const sb=()=>{g.ballOn=document.getElementById('ballSideInput').value+' '+document.getElementById('ballYardInput').value;normalizeGoal(g);save()};document.getElementById('ballSideInput').onchange=sb;document.getElementById('ballYardInput').onchange=sb;
 document.getElementById('undoBtn').onclick=()=>{if(!g.plays.length)return;const p=g.plays.pop();g.down=p.beforeDown??g.down;g.toGo=p.beforeToGo??g.toGo;g.possession=p.beforePossession??g.possession;g.ballOn=p.beforeBallOn??g.ballOn;if(p.beforeIraScore!==undefined)g.iraScore=p.beforeIraScore;if(p.beforeOppScore!==undefined)g.oppScore=p.beforeOppScore;save();toast('Last play undone')};document.querySelectorAll('[data-delplay]').forEach(b=>b.onclick=()=>{g.plays=g.plays.filter(p=>p.id!==b.dataset.delplay);save()});
 let nt;const n=document.getElementById('radioNotes');n.oninput=()=>{g.notes=n.value;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));clearTimeout(nt);nt=setTimeout(()=>{schedulePublish();const x=document.getElementById('notesSaved');if(x)x.textContent='Saved'},500)};
 let pt;const u=document.getElementById('publicUpdate');u.oninput=()=>{g.publicUpdate=u.value;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));clearTimeout(pt);pt=setTimeout(schedulePublish,650)};document.getElementById('clearPublicUpdate').onclick=()=>{g.publicUpdate='';save()};
}
let flowCtx=null;
function touchdownFlow(team){flowCtx={team,stage:'pat'};renderFlowDialog()}
function renderFlowDialog(){const d=document.getElementById('flowDialog'),m=document.getElementById('flowMount'),g=ensureGame(),team=flowCtx.team,other=team==='ira'?'opp':'ira';if(flowCtx.stage==='pat')m.innerHTML=`<div class="eyebrow">TOUCHDOWN — CONVERSION</div><h2>${esc(teamLabel(team))}</h2><div class="big-choice-grid"><button data-pat="1" data-desc="Run PAT good">1 PT — RUN</button><button data-pat="1" data-desc="Pass PAT good">1 PT — PASS</button><button data-pat="2" data-desc="Kick PAT good">2 PT — KICK</button><button class="ghost" data-pat="0" data-desc="PAT no good / skipped">NO GOOD / SKIP</button></div>`;else if(flowCtx.stage==='kicktype')m.innerHTML=`<div class="eyebrow">KICKOFF</div><h2>Kick type</h2><div class="big-choice-grid two"><button data-kicktype="normal">NORMAL KICK</button><button data-kicktype="onside">ONSIDE KICK</button></div>`;else{const recv=other,chosen=flowCtx.recoveryTeam||recv,bp={side:'Own',yard:20};m.innerHTML=`<div class="eyebrow">${flowCtx.kicktype==='onside'?'ONSIDE':'NORMAL'} KICK — RESULT</div><h2>Who recovered?</h2><div class="big-choice-grid two"><button data-kickrecover="${recv}" class="${chosen===recv?'selected':''}">RECEIVING TEAM<br><small>${esc(teamShort(recv))}</small></button><button data-kickrecover="${team}" class="${chosen===team?'selected':''}">KICKING TEAM<br><small>${esc(teamShort(team))}</small></button></div><label>Who recovered? (optional)<select id="kickRecoverPlayer">${playerOptions(chosen)}</select></label><div class="form-grid two-col"><label>Ball side<select id="kickBallSide"><option>Own</option><option>Opp</option></select></label><label>Yard line<select id="kickBallYard">${Array.from({length:40},(_,i)=>i+1).map(n=>`<option ${n===20?'selected':''}>${n}</option>`).join('')}</select></label></div><button id="finishKickBtn" class="full-primary">START NEXT SERIES</button>`}
 d.showModal();m.querySelectorAll('[data-pat]').forEach(b=>b.onclick=()=>{const pts=Number(b.dataset.pat),beforeIra=g.iraScore,beforeOpp=g.oppScore;if(pts){if(team==='ira')g.iraScore+=pts;else g.oppScore+=pts}g.plays.push({id:uid(),at:new Date().toISOString(),type:'score',team,points:pts,description:b.dataset.desc,beforeIraScore:beforeIra,beforeOppScore:beforeOpp,beforeDown:g.down,beforeToGo:g.toGo,beforePossession:g.possession,beforeBallOn:g.ballOn});flowCtx.stage='kicktype';renderFlowDialog()});m.querySelectorAll('[data-kicktype]').forEach(b=>b.onclick=()=>{flowCtx.kicktype=b.dataset.kicktype;flowCtx.stage='kickresult';flowCtx.recoveryTeam=other;renderFlowDialog()});m.querySelectorAll('[data-kickrecover]').forEach(b=>b.onclick=()=>{flowCtx.recoveryTeam=b.dataset.kickrecover;renderFlowDialog()});const finish=m.querySelector('#finishKickBtn');if(finish)finish.onclick=()=>{g.possession=flowCtx.recoveryTeam||other;g.ballOn=document.getElementById('kickBallSide').value+' '+document.getElementById('kickBallYard').value;seriesReset(g);g.plays.push({id:uid(),at:new Date().toISOString(),type:'kickoff',team,kicktype:flowCtx.kicktype,recoveryTeam:g.possession,recoveredBy:document.getElementById('kickRecoverPlayer').value,ballOn:g.ballOn});save();d.close();toast('Next series ready')}}

function teamPlayerTable(team,players){const rows=Object.entries(players||{}).map(([id,x])=>({id,...x})).filter(x=>Object.values(x).some(v=>typeof v==='number'&&v!==0)).sort((a,b)=>((b.rushYds||0)+(b.passYds||0)+(b.recYds||0)+(b.tackles||0)*5)-((a.rushYds||0)+(a.passYds||0)+(a.recYds||0)+(a.tackles||0)*5));if(!rows.length)return '<p class="muted">No player stats yet.</p>';return `<div class="table-wrap"><table><thead><tr><th>Player</th><th>Rush</th><th>Pass</th><th>Rec</th><th>Sack</th><th>Tkl</th><th>INT</th><th>FR</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(playerName(team,x.id))}</td><td>${x.rushAtt||0}-${x.rushYds||0}</td><td>${x.passComp||0}/${x.passAtt||0}-${x.passYds||0}</td><td>${x.rec||0}-${x.recYds||0}</td><td>${Number(x.sacks||0).toFixed((x.sacks||0)%1?1:0)}</td><td>${Number(x.tackles||0).toFixed((x.tackles||0)%1?1:0)}</td><td>${x.defInt||0}</td><td>${x.fumbleRec||0}</td></tr>`).join('')}</tbody></table></div>`}
function renderStats(){const el=document.getElementById('stats');if(!el)return;const g=ensureGame(),st=calc();el.innerHTML=`<div class="card hero stats-wide"><div class="eyebrow">RADIO BOOTH</div><h2>Live Stats — IRA ${g.iraScore}, ${esc(g.opponent)} ${g.oppScore}</h2></div><div class="stats-stack"><div class="card stats-card"><h2>Game Comparison</h2>${comparisonTable(st)}</div><div class="card stats-card"><h2>Ira Bulldogs Player Stats</h2>${teamPlayerTable('ira',st.ira.players)}</div><div class="card stats-card"><h2>${esc(g.opponent)} Player Stats</h2>${teamPlayerTable('opp',st.opp.players)}</div><div class="card stats-card"><h2>Radio Notes</h2>${broadcastNotes(st).map(x=>`<div class="broadcast-note">${esc(x)}</div>`).join('')}</div></div>`}
function comparisonTable(st){const g=ensureGame();return `<div class="table-wrap"><table><thead><tr><th>Stat</th><th class="num">Ira Bulldogs</th><th class="num">${esc(g.opponent)}</th></tr></thead><tbody>${[['Score','score'],['Rushing yards','rushYds'],['Passing yards','passYds'],['Total yards','total'],['First downs','firstDowns'],['Turnovers','turnovers'],['Plays','plays']].map(([label,key])=>{const a=key==='total'?st.ira.rushYds+st.ira.passYds:st.ira[key],b=key==='total'?st.opp.rushYds+st.opp.passYds:st.opp[key];return `<tr><td>${label}</td><td class="num">${a}</td><td class="num">${b}</td></tr>`}).join('')}</tbody></table></div>`}

function renderRosters(){const d=document.getElementById('roster');d.innerHTML=`<div class="grid two"><div class="card"><h2>Ira Roster</h2>${rosterEditor('ira')}</div><div class="card"><h2>${esc(ensureGame().opponent)} Roster</h2>${rosterEditor('opp')}</div></div>`;d.querySelectorAll('[data-addroster]').forEach(b=>b.onclick=()=>addRoster(b.dataset.addroster));d.querySelectorAll('[data-delroster]').forEach(b=>b.onclick=()=>{const [t,id]=b.dataset.delroster.split(':');state.rosters[t]=state.rosters[t].filter(p=>p.id!==id);save()});d.querySelectorAll('[data-editroster]').forEach(b=>b.onclick=()=>openRosterEdit(...b.dataset.editroster.split(':')))}
function openRosterEdit(team,id){const p=state.rosters[team].find(x=>x.id===id);if(!p)return;const d=document.getElementById('rosterDialog');d.dataset.team=team;d.dataset.id=id;document.getElementById('editRosterNum').value=p.number;document.getElementById('editRosterName').value=p.name;document.getElementById('editRosterPos').value=p.position||'';d.showModal()}
document.getElementById('saveRosterEdit').onclick=()=>{const d=document.getElementById('rosterDialog'),p=state.rosters[d.dataset.team]?.find(x=>x.id===d.dataset.id);if(!p)return;p.number=document.getElementById('editRosterNum').value.trim();p.name=document.getElementById('editRosterName').value.trim();p.position=document.getElementById('editRosterPos').value.trim();save();d.close();toast('Player updated')};

function researchCard(s){const pd=(state.pregameData||{})[s.week]||{},o=pd.opponent||{};return `<div class="card"><div class="inline"><div><div class="eyebrow">OPPONENT RESEARCH</div><h2>${esc(s.opponent)}</h2></div><button id="researchBtn">Refresh Pregame Research</button></div><div class="summary-grid research-summary"><div class="summary-item"><span class="kicker">Overall rank</span><strong>${o.rank?'#'+o.rank:(s.rank?'#'+s.rank:'—')}</strong></div><div class="summary-item"><span class="kicker">Rating</span><strong>${o.rating||'—'}</strong></div><div class="summary-item"><span class="kicker">Record</span><strong>${esc(o.record||'—')}</strong></div><div class="summary-item"><span class="kicker">Coach</span><strong>${esc(o.coach||'—')}</strong></div></div><h3>Projection / Numbers to Know</h3><p>${esc(pd.projection||'Refresh research when online to cache opponent information for the broadcast.')}</p><h3>Common Opponents</h3><p>${esc(pd.commonOpponents||'No common-opponent comparison cached yet.')}</p><h3>Current Week / Recent Results</h3>${(pd.results||[]).length?pd.results.slice(0,5).map(x=>`<div class="broadcast-note">${esc(x)}</div>`).join(''):'<p class="muted">No recent results cached yet.</p>'}<h3>Players / Storylines to Watch</h3>${(pd.webNotes||[]).length?pd.webNotes.slice(0,6).map(x=>`<div class="broadcast-note">${esc(x)}</div>`).join(''):'<p class="muted">Player information will appear when public web sources provide it. The app will not invent names.</p>'}<p class="small muted">Cached for offline use${pd.updated?' • '+new Date(pd.updated).toLocaleString():''}.</p></div>`}
function renderPregame(){const s=currentSchedule(),tp=talkingPoints(),scheduleRows=state.schedule.map(x=>`<div class="schedule-row ${x.week===Number(state.selectedWeek)?'current':''}" data-week="${x.week}"><div><strong>Wk ${x.week}</strong><div class="small muted">${fmtDate(x.date)}</div></div><div><strong>${esc(x.opponent)}</strong><div class="small muted">${esc(x.time||'')}</div></div><div>${x.rank?`<span class="rank">#${x.rank}</span>`:''}</div><div>${esc(x.site)}${x.district?' • District':''}</div></div>`).join('');document.getElementById('pregame').innerHTML=`<div class="card hero"><div class="hero-row"><div class="matchup"><div class="eyebrow">WEEK ${s.week} • PREGAME</div><h2>IRA BULLDOGS vs ${esc(s.opponent)}</h2><div class="matchup-meta"><span class="pill">${fmtDate(s.date)} ${esc(s.time)}</span><span class="pill">${esc(s.site)}</span>${s.district?'<span class="pill">DISTRICT</span>':''}</div></div><div><div class="kicker">Ira SixManFootball rank</div><div style="font-size:2.1rem;font-weight:900">#${state.teamInfo.rank}</div></div></div></div><div class="grid two" style="margin-top:16px"><div class="card"><div class="inline"><h2>2026 Schedule</h2><button id="syncBtn">Safe Schedule Sync</button></div><div class="schedule-list">${scheduleRows}</div></div><div class="grid">${researchCard(s)}<div class="card"><h2>Broadcast Talking Point</h2><div class="talking-point">${esc(tp[talkingIndex%tp.length]||'')}</div><div class="talking-controls"><button id="nextTalkingBtn">Next Talking Point</button></div></div></div></div>`;document.querySelectorAll('.schedule-row').forEach(el=>el.onclick=()=>{state.selectedWeek=Number(el.dataset.week);save()});document.getElementById('syncBtn').onclick=syncSixMan;document.getElementById('researchBtn').onclick=refreshResearch;document.getElementById('nextTalkingBtn').onclick=()=>{talkingIndex++;renderPregame()}}
async function refreshResearch(){const url=(state.settings.syncUrl||'').trim(),s=currentSchedule();if(!url){toast('Add Apps Script URL in Settings');return}const b=document.getElementById('researchBtn');b.disabled=true;b.textContent='Researching…';try{const x=await jsonp(url,{action:'research',opponent:s.opponent,week:s.week,_:Date.now()});if(!x?.ok)throw new Error(x?.error||'Research failed');state.pregameData=state.pregameData||{};state.pregameData[s.week]={...(state.pregameData[s.week]||{}),...x.data,updated:new Date().toISOString()};save('Pregame research cached');toast('Opponent research cached for offline use')}catch(e){console.error(e);toast('Research unavailable; existing cache kept')}finally{renderPregame()}}

function nextGameCard(next){if(!next)return '<p class="muted">No later regular-season game is cached.</p>';const pd=(state.pregameData||{})[next.week]||{},o=pd.opponent||{};return `<h3>${esc(next.opponent)}</h3><p><strong>${fmtDate(next.date)} • ${esc(next.time)} • ${esc(next.site)}</strong>${next.district?' • District':''}</p><div class="summary-grid"><div class="summary-item"><span class="kicker">Rank</span><strong>${o.rank?'#'+o.rank:(next.rank?'#'+next.rank:'—')}</strong></div><div class="summary-item"><span class="kicker">Projection</span><strong>${esc(pd.projection||'Refresh in Pregame')}</strong></div></div><h3>What they did this week</h3>${(pd.results||[]).length?pd.results.slice(0,3).map(x=>`<div class="broadcast-note">${esc(x)}</div>`).join(''):'<p class="muted">Refresh that opponent’s Pregame Research to cache the latest score/matchup.</p>'}<h3>Common Opponents</h3><p>${esc(pd.commonOpponents||'No cached comparison yet.')}</p>`}

function publicPayload(){const g=ensureGame();return {version:4,updated:new Date().toISOString(),broadcasterState:cloudState(),team:{name:'Ira Bulldogs',rank:state.teamInfo.rank},game:{week:g.week,opponent:g.opponent,date:g.date,time:g.time,site:g.site,quarter:g.quarter,clock:g.clock,possession:g.possession,iraScore:g.iraScore,oppScore:g.oppScore,final:g.final,latestUpdate:g.publicUpdate||''},listenUrl:state.settings.listenUrl||''}}

function resetCurrentTestData(){const g=ensureGame(),keep={week:g.week,opponent:g.opponent,date:g.date,time:g.time,site:g.site};state.games[gameKey()]={...keep,quarter:1,clock:'10:00',down:1,toGo:15,ballOn:'Own 20',possession:'ira',iraScore:0,oppScore:0,plays:[],notes:'',publicUpdate:'',final:false,created:new Date().toISOString()};save('Test/game data reset');toast('Current game cleared — rosters and setup kept')}
// Settings reset button and clock dialog actions are wired after DOM exists.
document.getElementById('resetTestBtn').onclick=()=>{if(confirm('Clear ONLY this game’s score, clock, plays, stats and notes? Rosters, schedule, cloud URL and settings will be kept.'))resetCurrentTestData()};document.getElementById('saveClockBtn').onclick=()=>{commitClock('clockPick');save();document.getElementById('clockDialog').close();toast('Clock updated')};
