const STORAGE_KEY='ira_radio_game_center_v1';
const DEFAULT_SCHEDULE=[
 {week:1,date:'2026-08-28',time:'7:30 PM',opponent:'Roby Lions',rank:80,site:'Away',district:false},
 {week:2,date:'2026-09-04',time:'7:30 PM',opponent:'Jayton Jaybirds',rank:13,site:'Home',district:false},
 {week:3,date:'2026-09-11',time:'7:30 PM',opponent:'Garden City Bearkats',rank:42,site:'Away',district:false},
 {week:4,date:'2026-09-18',time:'7:00 PM',opponent:'Abilene Christian Panthers',rank:96,site:'Home',district:false},
 {week:5,date:'2026-09-25',time:'7:30 PM',opponent:'Meadow Broncos',rank:130,site:'Away',district:false},
 {week:6,date:'',time:'',opponent:'OPEN / BYE',rank:null,site:'',district:false},
 {week:7,date:'2026-10-09',time:'7:30 PM',opponent:'Sands Mustangs',rank:23,site:'Home',district:true},
 {week:8,date:'2026-10-16',time:'7:00 PM',opponent:'Klondike Cougars',rank:16,site:'Away',district:true},
 {week:9,date:'2026-10-23',time:'7:30 PM',opponent:"O'Donnell Eagles",rank:86,site:'Home',district:true},
 {week:10,date:'2026-10-30',time:'7:00 PM',opponent:'Borden County Coyotes',rank:3,site:'Away',district:true},
 {week:11,date:'2026-11-06',time:'7:00 PM',opponent:'Westbrook Wildcats',rank:24,site:'Home',district:true}
];
const HISTORY=[{year:2025,record:'8-3'},{year:2024,record:'7-4'},{year:2023,record:'6-4'},{year:2022,record:'8-3'},{year:2021,record:'7-3'},{year:2020,record:'8-3'},{year:2019,record:'11-1'},{year:2018,record:'10-1'},{year:2014,record:'12-1'},{year:2013,record:'12-1'},{year:2011,record:'12-1'},{year:2010,record:'12-1'}];
const blankTeamStats=()=>({rushYds:0,passYds:0,firstDowns:0,turnovers:0,plays:0,score:0,possessions:0});
const initialState=()=>({
 version:2, settings:{syncUrl:'',publishKey:'IRA-RADIO-2026-8f3a1d',listenUrl:''}, teamInfo:{name:'Ira Bulldogs',rank:25,leagueRank:16,rating:315.75,league:'UIL Division I',district:'District 5',coach:'Jess Wall',stadium:'Ira Bulldogs Field',colors:'Black and Orange',updated:null},
 schedule:DEFAULT_SCHEDULE, history:HISTORY, selectedWeek:1,
 games:{},
 rosters:{ira:[],opp:[]}
});
let state=load();
let talkingIndex=0;

function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return x?mergeState(initialState(),x):initialState()}catch{return initialState()}}
function mergeState(base,saved){return {...base,...saved,settings:{...base.settings,...(saved.settings||{})},teamInfo:{...base.teamInfo,...(saved.teamInfo||{})},rosters:{...base.rosters,...(saved.rosters||{})}}}
function save(msg='Saved locally'){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));const e=document.getElementById('saveState');if(e)e.textContent=msg;renderAll();schedulePublish()}
function currentSchedule(){return state.schedule.find(x=>x.week===Number(state.selectedWeek))||state.schedule[0]}
function gameKey(){return `2026-w${state.selectedWeek}`}
function ensureGame(){const s=currentSchedule();if(!state.games[gameKey()]) state.games[gameKey()]={week:s.week,opponent:s.opponent,date:s.date,time:s.time,site:s.site,quarter:1,clock:'10:00',down:1,toGo:15,ballOn:'Own 20',possession:'ira',iraScore:0,oppScore:0,plays:[],notes:'',final:false,created:new Date().toISOString()};return state.games[gameKey()]}

let publishTimer=null;
function publicPayload(){
 const g=ensureGame(),st=calc();
 const leaders=(team,key,attKey)=>Object.entries(st[team].players||{}).map(([id,x])=>({id,...x})).sort((a,b)=>(b[key]||0)-(a[key]||0)).filter(x=>(x[key]||0)>0).slice(0,3).map(x=>({name:playerName(team,x.id),value:x[key]||0,attempts:attKey?(x[attKey]||0):undefined}));
 return {version:1,updated:new Date().toISOString(),team:{name:state.teamInfo.name,rank:state.teamInfo.rank},game:{week:g.week,opponent:g.opponent,date:g.date,time:g.time,site:g.site,quarter:g.quarter,clock:g.clock,down:g.down,toGo:g.toGo,ballOn:g.ballOn,possession:g.possession,iraScore:g.iraScore,oppScore:g.oppScore,final:g.final},stats:{ira:{rushYds:st.ira.rushYds,passYds:st.ira.passYds,totalYds:st.ira.rushYds+st.ira.passYds,firstDowns:st.ira.firstDowns,turnovers:st.ira.turnovers,plays:st.ira.plays},opp:{rushYds:st.opp.rushYds,passYds:st.opp.passYds,totalYds:st.opp.rushYds+st.opp.passYds,firstDowns:st.opp.firstDowns,turnovers:st.opp.turnovers,plays:st.opp.plays}},leaders:{rushing:leaders('ira','rushYds','rushAtt'),passing:leaders('ira','passYds','passAtt'),receiving:leaders('ira','recYds','rec')},plays:g.plays.slice(-100).map((p,i)=>({seq:g.plays.length-Math.min(100,g.plays.length)+i+1,text:describePlay(p),at:p.at||null})),listenUrl:state.settings.listenUrl||''};
}
function schedulePublish(){clearTimeout(publishTimer);publishTimer=setTimeout(publishPublic,900)}
async function publishPublic(){
 const url=(state.settings.syncUrl||'').trim(),key=(state.settings.publishKey||'').trim();
 const status=document.getElementById('publicStatus');
 if(!url||!key){if(status)status.textContent='Public: setup needed';return}
 if(!navigator.onLine){if(status)status.textContent='Public: queued offline';return}
 try{if(status)status.textContent='Public: syncing…';const body=new URLSearchParams({action:'publish',key,payload:JSON.stringify(publicPayload())});await fetch(url,{method:'POST',mode:'no-cors',body});if(status)status.textContent='Public: updated';}
 catch(e){if(status)status.textContent='Public: queued';}
}
window.addEventListener('online',()=>schedulePublish());

function fmtDate(d){if(!d)return 'Open week';return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function playerName(team,id){const p=(state.rosters[team]||[]).find(p=>p.id===id);return p?`#${p.number} ${p.name}`:'Unknown player'}
function teamLabel(t){return t==='ira'?'Ira':'Opponent'}
function uid(){return Math.random().toString(36).slice(2,10)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}

function calc(){const g=ensureGame();const teams={ira:{...blankTeamStats(),players:{}},opp:{...blankTeamStats(),players:{}}};
 const pstat=(t,id)=>{if(!id)return null;if(!teams[t].players[id])teams[t].players[id]={rushAtt:0,rushYds:0,rushTD:0,passAtt:0,passComp:0,passYds:0,passTD:0,int:0,rec:0,recYds:0,recTD:0,points:0,tackles:0,sacks:0};return teams[t].players[id]};
 for(const p of g.plays){const t=teams[p.team],other=teams[p.team==='ira'?'opp':'ira'];if(!t)continue;
   if(['run','pass','sack'].includes(p.type))t.plays++;
   if(p.type==='run'){t.rushYds+=p.yards||0;const ps=pstat(p.team,p.runner);ps.rushAtt++;ps.rushYds+=p.yards||0;if(p.firstDown)t.firstDowns++;if(p.touchdown){ps.rushTD++;ps.points+=6;t.score+=6}}
   if(p.type==='pass'){const qb=pstat(p.team,p.passer);qb.passAtt++;if(p.complete){qb.passComp++;qb.passYds+=p.yards||0;t.passYds+=p.yards||0;const r=pstat(p.team,p.receiver);r.rec++;r.recYds+=p.yards||0;if(p.firstDown)t.firstDowns++;if(p.touchdown){qb.passTD++;r.recTD++;r.points+=6;t.score+=6}}if(p.interception){qb.int++;t.turnovers++;other.possessions++}}
   if(p.type==='sack'){t.passYds+=p.yards||0}
   if(p.type==='turnover'){t.turnovers++;other.possessions++}
   if(p.type==='score'){t.score+=p.points||0;const ps=pstat(p.team,p.scorer);if(ps)ps.points+=p.points||0}
   if(p.type==='possession')t.possessions++;
 }
 // Manual scoreboard remains authoritative; play-derived score is useful but not forced.
 teams.ira.score=g.iraScore;teams.opp.score=g.oppScore;return teams;
}

function renderAll(){renderPregame();renderLive();renderHalftime();renderPostgame();renderRosters()}
function renderPregame(){const s=currentSchedule(),g=ensureGame();const tp=talkingPoints();const scheduleRows=state.schedule.map(x=>`<div class="schedule-row ${x.week===Number(state.selectedWeek)?'current':''}" data-week="${x.week}"><div><strong>Wk ${x.week}</strong><div class="small muted">${fmtDate(x.date)}</div></div><div><strong>${esc(x.opponent)}</strong><div class="small muted">${esc(x.time||'')}</div></div><div>${x.rank?`<span class="rank">#${x.rank}</span>`:''}</div><div class="location">${esc(x.site)}${x.district?' • District':''}</div></div>`).join('');
 document.getElementById('pregame').innerHTML=`
 <div class="card hero"><div class="hero-row"><div class="matchup"><div class="eyebrow">WEEK ${s.week} • PREGAME</div><h2>IRA vs ${esc(s.opponent.replace(/\s+(Lions|Jaybirds|Bearkats|Panthers|Broncos|Mustangs|Cougars|Eagles|Coyotes|Wildcats)$/,''))}</h2><div class="matchup-meta"><span class="pill">${fmtDate(s.date)} ${esc(s.time)}</span><span class="pill">${esc(s.site)}</span>${s.district?'<span class="pill">DISTRICT</span>':''}</div></div><div><div class="kicker">SixManFootball snapshot</div><div style="font-size:2.1rem;font-weight:900">#${state.teamInfo.rank}</div><div class="muted" style="color:#bbb">Ira overall rank</div></div></div></div>
 <div class="grid two" style="margin-top:16px"><div class="card"><div class="inline" style="justify-content:space-between"><h2>2026 Schedule</h2><button id="syncBtn">Sync SixManFootball</button></div><div class="schedule-list">${scheduleRows}</div></div>
 <div class="grid"><div class="card"><h2>Broadcast Talking Point</h2><div class="talking-point">${esc(tp[talkingIndex%tp.length]||'Add roster and game data to create talking points.')}</div><div class="talking-controls"><button id="nextTalkingBtn">Next Talking Point</button><button class="ghost" id="copyTalkingBtn">Copy</button></div></div>
 <div class="card"><h3>Ira Program Snapshot</h3><div class="summary-grid"><div class="summary-item"><span class="kicker">Coach</span><strong>${esc(state.teamInfo.coach)}</strong></div><div class="summary-item"><span class="kicker">League</span><strong>${esc(state.teamInfo.league)}</strong></div><div class="summary-item"><span class="kicker">District</span><strong>${esc(state.teamInfo.district)}</strong></div><div class="summary-item"><span class="kicker">Rating</span><strong>${state.teamInfo.rating}</strong></div></div><p class="small muted" style="margin-top:10px">Cached data${state.teamInfo.updated?' • updated '+new Date(state.teamInfo.updated).toLocaleString():''}. The broadcast tools continue working offline.</p></div></div></div>`;
 document.querySelectorAll('.schedule-row').forEach(el=>el.onclick=()=>{state.selectedWeek=Number(el.dataset.week);save()});
 document.getElementById('nextTalkingBtn').onclick=()=>{talkingIndex++;renderPregame()};
 document.getElementById('copyTalkingBtn').onclick=()=>navigator.clipboard?.writeText(tp[talkingIndex%tp.length]||'').then(()=>toast('Talking point copied'));
 document.getElementById('syncBtn').onclick=syncSixMan;
}
function talkingPoints(){const s=currentSchedule(),games=Object.values(state.games),completed=games.filter(g=>g.final);const pts=[];
 pts.push(`Ira enters 2026 ranked #${state.teamInfo.rank} overall by SixManFootball with a rating of ${state.teamInfo.rating}.`);
 pts.push(`Tonight's opponent is ${s.opponent}${s.rank?`, currently listed #${s.rank}`:''}. This is a ${s.site.toLowerCase()||'scheduled'} game for Ira${s.district?' and a district matchup':''}.`);
 pts.push(`Jess Wall is the Ira head coach. The Bulldogs compete in ${state.teamInfo.league}, ${state.teamInfo.district}.`);
 pts.push(`Ira finished 8-3 in 2025. The program also posted 12-1 seasons in 2010, 2011, 2013 and 2014.`);
 const next=state.schedule.find(x=>x.week>s.week&&x.opponent!=='OPEN / BYE');if(next)pts.push(`Next up for Ira: ${next.opponent} on ${fmtDate(next.date)} at ${next.time}, ${next.site.toLowerCase()}.`);
 if(completed.length){const pf=completed.reduce((a,g)=>a+g.iraScore,0),pa=completed.reduce((a,g)=>a+g.oppScore,0);pts.push(`Through ${completed.length} completed game${completed.length===1?'':'s'} tracked here, Ira is averaging ${(pf/completed.length).toFixed(1)} points and allowing ${(pa/completed.length).toFixed(1)}.`)}
 return pts;
}
async function syncSixMan(){const url=(state.settings.syncUrl||'').trim();if(!url){toast('Add the Apps Script sync URL in Settings');document.getElementById('settingsDialog').showModal();return}const btn=document.getElementById('syncBtn');btn.disabled=true;btn.textContent='Syncing…';try{const r=await fetch(url+(url.includes('?')?'&':'?')+'action=team');if(!r.ok)throw new Error('Sync failed');const data=await r.json();if(data.schedule?.length)state.schedule=data.schedule;if(data.teamInfo)state.teamInfo={...state.teamInfo,...data.teamInfo,updated:new Date().toISOString()};save('Synced');toast('SixManFootball data refreshed')}catch(e){toast('Could not sync; cached data kept')}finally{renderPregame()}}

function renderLive(){const g=ensureGame(),st=calc();document.getElementById('live').innerHTML=`<div class="grid live-layout">
 <div class="grid"><div class="card hero"><div class="eyebrow">LIVE GAME • WEEK ${g.week}</div><div class="scoreboard"><div><div class="team-name">IRA</div><div class="team-score">${g.iraScore}</div></div><div class="score-dash">–</div><div><div class="team-name">${esc(g.opponent)}</div><div class="team-score">${g.oppScore}</div></div></div></div>
 <div class="card"><div class="possession"><button data-pos="ira" class="${g.possession==='ira'?'active':''}">Ira Ball</button><button data-pos="opp" class="${g.possession==='opp'?'active':''}">Opponent Ball</button></div><div class="game-meta"><label>Quarter<select id="quarterSel">${[1,2,3,4,5].map(q=>`<option ${g.quarter===q?'selected':''}>${q}</option>`).join('')}</select></label><label>Clock<input id="clockInput" value="${esc(g.clock)}"></label><label>Down<select id="downSel">${[1,2,3,4].map(x=>`<option ${g.down===x?'selected':''}>${x}</option>`).join('')}</select></label><label>To Go<input id="toGoInput" type="number" value="${g.toGo}"></label><label>Ball On<input id="ballOnInput" value="${esc(g.ballOn)}"></label></div>
 <div class="live-controls"><button class="run" data-play="run">RUN</button><button class="pass" data-play="pass">PASS</button><button data-play="sack">SACK</button><button class="penalty" data-play="penalty">PENALTY</button><button data-play="turnover">TURNOVER</button><button class="score" data-play="score">SCORE</button><button data-play="possession">NEW DRIVE</button><button class="dark" id="undoBtn">UNDO LAST</button></div></div>
 <div class="card"><div class="inline"><div><h2>Play-by-Play</h2><div class="small muted">Newest play first</div></div><button class="ghost" id="clearGameBtn">Reset Game</button></div><div class="play-log">${[...g.plays].reverse().map((p,i)=>`<div class="play-row"><div class="seq">#${g.plays.length-i}</div><div>${esc(describePlay(p))}</div><button class="ghost" data-delplay="${p.id}">Delete</button></div>`).join('')||'<p class="muted">No plays entered yet.</p>'}</div></div></div>
 <div class="grid"><div class="card"><h2>Radio Dashboard</h2><div class="stat-strip"><div class="stat-box"><strong>${st.ira.rushYds}</strong><span>Rush yds</span></div><div class="stat-box"><strong>${st.ira.passYds}</strong><span>Pass yds</span></div><div class="stat-box"><strong>${st.ira.rushYds+st.ira.passYds}</strong><span>Total yds</span></div><div class="stat-box"><strong>${st.ira.firstDowns}</strong><span>1st downs</span></div><div class="stat-box"><strong>${st.ira.turnovers}</strong><span>Turnovers</span></div><div class="stat-box"><strong>${st.ira.plays?((st.ira.rushYds+st.ira.passYds)/st.ira.plays).toFixed(1):'0.0'}</strong><span>Yds/play</span></div></div></div>
 <div class="card"><h2>Broadcast Notes</h2>${broadcastNotes(st).map(x=>`<div class="broadcast-note">${esc(x)}</div>`).join('')||'<p class="muted">Notes appear as you enter plays.</p>'}</div>
 <div class="card"><h2>Ira Leaders</h2>${leadersTable(st.ira.players)}</div>
 <div class="card"><h2>Score Controls</h2><div class="grid two"><label>Ira score<input id="iraScore" type="number" value="${g.iraScore}"></label><label>Opponent score<input id="oppScore" type="number" value="${g.oppScore}"></label></div></div></div></div>`;
 document.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{g.possession=b.dataset.pos;save()});document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>openPlay(b.dataset.play));
 ['quarterSel','clockInput','downSel','toGoInput','ballOnInput','iraScore','oppScore'].forEach(id=>document.getElementById(id).onchange=e=>{const map={quarterSel:'quarter',clockInput:'clock',downSel:'down',toGoInput:'toGo',ballOnInput:'ballOn',iraScore:'iraScore',oppScore:'oppScore'};let v=e.target.value;if(['quarterSel','downSel','toGoInput','iraScore','oppScore'].includes(id))v=Number(v);g[map[id]]=v;save()});
 document.getElementById('undoBtn').onclick=()=>{if(g.plays.length){g.plays.pop();save();toast('Last play removed')}};document.querySelectorAll('[data-delplay]').forEach(b=>b.onclick=()=>{g.plays=g.plays.filter(p=>p.id!==b.dataset.delplay);save()});
 document.getElementById('clearGameBtn').onclick=()=>{if(confirm('Reset this game? This removes all plays and scores for the selected week.')){delete state.games[gameKey()];save();toast('Game reset')}};
}
function playerOptions(team,selected=''){const list=state.rosters[team]||[];return `<option value="">Select player</option>`+list.slice().sort((a,b)=>Number(a.number)-Number(b.number)).map(p=>`<option value="${p.id}" ${selected===p.id?'selected':''}>#${esc(p.number)} ${esc(p.name)}</option>`).join('')}
function openPlay(type){const g=ensureGame(),team=g.possession;const d=document.getElementById('playDialog'),fields=document.getElementById('playFormFields');document.getElementById('playDialogTitle').textContent=type[0].toUpperCase()+type.slice(1);document.getElementById('playDialogEyebrow').textContent=`${teamLabel(team).toUpperCase()} OFFENSE`;
 let html=`<input type="hidden" name="type" value="${type}"><input type="hidden" name="team" value="${team}">`;
 if(type==='run')html+=`<div class="form-grid"><label>Ball carrier<select name="runner" required>${playerOptions(team)}</select></label><label>Yards<input name="yards" type="number" value="0" required></label><label>Result<select name="result"><option value="normal">Normal</option><option value="first">First down</option><option value="td">Touchdown</option><option value="fumble">Fumble / turnover</option></select></label></div>`;
 if(type==='pass')html+=`<div class="form-grid"><label>Passer<select name="passer" required>${playerOptions(team)}</select></label><label>Receiver<select name="receiver">${playerOptions(team)}</select></label><label>Result<select name="result"><option value="complete">Complete</option><option value="first">Complete • 1st down</option><option value="td">Touchdown</option><option value="incomplete">Incomplete</option><option value="int">Intercepted</option></select></label><label>Yards<input name="yards" type="number" value="0"></label></div>`;
 if(type==='sack')html+=`<div class="form-grid"><label>Yards lost<input name="yards" type="number" value="-5"></label></div>`;
 if(type==='penalty')html+=`<div class="form-grid"><label>Penalty<input name="penalty" placeholder="Holding"></label><label>Yards<input name="yards" type="number" value="5"></label><label>On<select name="penaltyOn"><option value="ira">Ira</option><option value="opp">Opponent</option></select></label></div>`;
 if(type==='turnover')html+=`<div class="form-grid"><label>Type<select name="turnoverType"><option>Fumble</option><option>Interception</option><option>Downs</option></select></label><label>Player<select name="scorer">${playerOptions(team)}</select></label></div>`;
 if(type==='score')html+=`<div class="form-grid"><label>Scorer<select name="scorer">${playerOptions(team)}</select></label><label>Points<select name="points"><option value="6">Touchdown • 6</option><option value="2">Kick PAT • 2</option><option value="1">Run/Pass PAT • 1</option><option value="4">Field Goal • 4</option><option value="2">Safety • 2</option></select></label><label>Description<input name="description" placeholder="PAT kick good"></label></div>`;
 if(type==='possession')html+=`<p>This records a new possession/drive for ${teamLabel(team)}.</p>`;
 html+=`<label style="display:grid;gap:6px;margin-top:12px">Radio note (optional)<input name="note" placeholder="Great block by #12, injury timeout, etc."></label>`;fields.innerHTML=html;d.showModal();
}
document.getElementById('playForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.target),p=Object.fromEntries(fd.entries());p.id=uid();p.at=new Date().toISOString();p.yards=Number(p.yards||0);p.points=Number(p.points||0);if(p.type==='run'){p.firstDown=p.result==='first';p.touchdown=p.result==='td';if(p.result==='fumble')p.turnover=true}if(p.type==='pass'){p.complete=['complete','first','td'].includes(p.result);p.firstDown=p.result==='first';p.touchdown=p.result==='td';p.interception=p.result==='int'}
 const g=ensureGame();g.plays.push(p);if(p.touchdown){if(p.team==='ira')g.iraScore+=6;else g.oppScore+=6}if(p.type==='score'&&p.points){if(p.team==='ira')g.iraScore+=p.points;else g.oppScore+=p.points}if(p.type==='turnover'||p.interception||p.turnover)g.possession=p.team==='ira'?'opp':'ira';save();document.getElementById('playDialog').close();toast('Play saved')});
function describePlay(p){const n=p.note?` — ${p.note}`:'';if(p.type==='run')return `${teamLabel(p.team)}: ${playerName(p.team,p.runner)} run ${p.yards>=0?'+':''}${p.yards} yd${p.yards===1?'':'s'}${p.touchdown?' TOUCHDOWN':''}${p.firstDown?' • 1st down':''}${n}`;if(p.type==='pass')return `${teamLabel(p.team)}: ${playerName(p.team,p.passer)} pass ${p.complete?'to '+playerName(p.team,p.receiver)+' '+p.yards+' yds':p.interception?'INTERCEPTED':'incomplete'}${p.touchdown?' TOUCHDOWN':''}${n}`;if(p.type==='sack')return `${teamLabel(p.team)}: sack ${p.yards} yards${n}`;if(p.type==='penalty')return `Penalty: ${p.penalty||'Penalty'} on ${teamLabel(p.penaltyOn)} for ${p.yards} yards${n}`;if(p.type==='turnover')return `${teamLabel(p.team)} turnover: ${p.turnoverType}${n}`;if(p.type==='score')return `${teamLabel(p.team)} scoring play: ${p.description||p.points+' points'}${p.scorer?' by '+playerName(p.team,p.scorer):''}${n}`;if(p.type==='possession')return `${teamLabel(p.team)} begins a new possession${n}`;return p.type}
function leadersTable(players){const rows=Object.entries(players).map(([id,s])=>({id,...s})).sort((a,b)=>(b.rushYds+b.recYds+b.passYds)-(a.rushYds+a.recYds+a.passYds)).slice(0,8);if(!rows.length)return '<p class="muted">No player stats yet.</p>';return `<div class="table-wrap"><table><thead><tr><th>Player</th><th class="num">Rush</th><th class="num">Pass</th><th class="num">Rec</th><th class="num">TD</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(playerName('ira',x.id))}</td><td class="num">${x.rushAtt}-${x.rushYds}</td><td class="num">${x.passComp}/${x.passAtt}-${x.passYds}</td><td class="num">${x.rec}-${x.recYds}</td><td class="num">${x.rushTD+x.passTD+x.recTD}</td></tr>`).join('')}</tbody></table></div>`}
function broadcastNotes(st){const notes=[],g=ensureGame(),ira=st.ira;notes.push(`Ira has ${ira.rushYds+ira.passYds} total yards on ${ira.plays} recorded offensive plays${ira.plays?`, ${((ira.rushYds+ira.passYds)/ira.plays).toFixed(1)} yards per play`:''}.`);if(ira.rushYds)notes.push(`The Bulldogs have rushed for ${ira.rushYds} yards.`);if(ira.passYds)notes.push(`Ira has ${ira.passYds} yards through the air.`);const players=Object.entries(ira.players).map(([id,s])=>({id,...s}));const r=players.sort((a,b)=>b.rushYds-a.rushYds)[0];if(r?.rushYds>=50)notes.push(`${playerName('ira',r.id)} leads Ira with ${r.rushYds} rushing yards on ${r.rushAtt} carries.`);if(g.iraScore!==g.oppScore)notes.push(`Ira ${g.iraScore>g.oppScore?'leads':'trails'} ${g.iraScore}-${g.oppScore} in the ${ordinalQuarter(g.quarter)}.`);return notes}
function ordinalQuarter(q){return q===1?'1st quarter':q===2?'2nd quarter':q===3?'3rd quarter':q===4?'4th quarter':'overtime'}
function comparisonTable(st){return `<div class="table-wrap"><table><thead><tr><th>Stat</th><th class="num">Ira</th><th class="num">Opponent</th></tr></thead><tbody>${[['Score','score'],['Rushing yards','rushYds'],['Passing yards','passYds'],['Total yards','total'],['First downs','firstDowns'],['Turnovers','turnovers'],['Plays','plays']].map(([label,key])=>{const a=key==='total'?st.ira.rushYds+st.ira.passYds:st.ira[key],b=key==='total'?st.opp.rushYds+st.opp.passYds:st.opp[key];return `<tr><td>${label}</td><td class="num">${a}</td><td class="num">${b}</td></tr>`}).join('')}</tbody></table></div>`}
function renderHalftime(){const g=ensureGame(),st=calc(),notes=broadcastNotes(st);document.getElementById('halftime').innerHTML=`<div class="card hero"><div class="eyebrow">HALFTIME SHOW</div><h2>IRA ${g.iraScore} — ${g.oppScore} ${esc(g.opponent)}</h2><p class="muted" style="color:#bbb">A ready-to-read first-half stat board generated from your play entries.</p></div><div class="grid two" style="margin-top:16px"><div class="card"><h2>First-Half Team Comparison</h2>${comparisonTable(st)}</div><div class="card"><h2>Ira Leaders</h2>${leadersTable(st.ira.players)}</div><div class="card"><h2>First-Half Story</h2>${notes.map(n=>`<div class="broadcast-note">${esc(n)}</div>`).join('')}</div><div class="card"><h2>Halftime Notes</h2><textarea id="halftimeNotes" placeholder="Band notes, scores from other games, sponsor reads, second-half keys…">${esc(g.notes||'')}</textarea><button id="saveHalftimeNotes" style="margin-top:8px">Save Notes</button></div></div>`;document.getElementById('saveHalftimeNotes').onclick=()=>{g.notes=document.getElementById('halftimeNotes').value;save();toast('Halftime notes saved')}}
function renderPostgame(){const g=ensureGame(),st=calc();const next=state.schedule.find(x=>x.week>g.week&&x.opponent!=='OPEN / BYE');const winner=g.iraScore>g.oppScore?'Ira wins':g.iraScore<g.oppScore?`${g.opponent} wins`:'Tie';document.getElementById('postgame').innerHTML=`<div class="card hero"><div class="eyebrow">${g.final?'FINAL':'POSTGAME PREVIEW'}</div><h2>${winner}: IRA ${g.iraScore}, ${esc(g.opponent)} ${g.oppScore}</h2><div class="talking-controls"><button id="finalBtn">${g.final?'Reopen Game':'Mark FINAL'}</button><button class="ghost" id="copyPostBtn">Copy Postgame Summary</button></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h2>By the Numbers</h2>${comparisonTable(st)}</div><div class="card"><h2>Game Leaders</h2>${leadersTable(st.ira.players)}</div><div class="card"><h2>Postgame Read</h2><div class="talking-point" id="postRead">${esc(postgameRead(g,st,next))}</div></div><div class="card"><h2>Up Next</h2>${next?`<p><strong>${esc(next.opponent)}</strong><br>${fmtDate(next.date)} • ${esc(next.time)} • ${esc(next.site)}${next.district?' • District':''}</p>`:'<p class="muted">No later regular-season game is cached.</p>'}</div></div>`;document.getElementById('finalBtn').onclick=()=>{g.final=!g.final;save();toast(g.final?'Game marked final':'Game reopened')};document.getElementById('copyPostBtn').onclick=()=>navigator.clipboard?.writeText(postgameRead(g,st,next)).then(()=>toast('Postgame summary copied'))}
function postgameRead(g,st,next){const total=st.ira.rushYds+st.ira.passYds;let s=`Final: Ira ${g.iraScore}, ${g.opponent} ${g.oppScore}. The Bulldogs finish with ${total} total yards — ${st.ira.rushYds} rushing and ${st.ira.passYds} passing — with ${st.ira.firstDowns} first downs and ${st.ira.turnovers} turnover${st.ira.turnovers===1?'':'s'}.`;const ps=Object.entries(st.ira.players).map(([id,x])=>({id,...x})).sort((a,b)=>b.rushYds-a.rushYds)[0];if(ps?.rushYds)s+=` ${playerName('ira',ps.id)} led Ira on the ground with ${ps.rushYds} yards on ${ps.rushAtt} carries.`;if(next)s+=` Ira's next scheduled game is against ${next.opponent} on ${fmtDate(next.date)} at ${next.time}.`;return s}
function renderRosters(){document.getElementById('roster').innerHTML=`<div class="grid two"><div class="card"><h2>Ira Roster</h2>${rosterEditor('ira')}</div><div class="card"><h2>Opponent Roster</h2><p class="small muted">Optional, but useful if you want opponent player statistics too.</p>${rosterEditor('opp')}</div></div>`;document.querySelectorAll('[data-addroster]').forEach(b=>b.onclick=()=>addRoster(b.dataset.addroster));document.querySelectorAll('[data-delroster]').forEach(b=>b.onclick=()=>{const [team,id]=b.dataset.delroster.split(':');state.rosters[team]=state.rosters[team].filter(p=>p.id!==id);save()})}
function rosterEditor(team){const rows=(state.rosters[team]||[]).slice().sort((a,b)=>Number(a.number)-Number(b.number)).map(p=>`<div class="roster-row"><div class="jersey">#${esc(p.number)}</div><div><strong>${esc(p.name)}</strong><div class="small muted">${esc(p.position||'')}</div></div><button class="ghost" data-delroster="${team}:${p.id}">Delete</button></div>`).join('');return `<div class="form-grid" style="grid-template-columns:90px 1fr 130px"><label>#<input id="${team}Num" inputmode="numeric"></label><label>Name<input id="${team}Name" placeholder="First Last"></label><label>Position<input id="${team}Pos" placeholder="RB/QB/E"></label></div><button data-addroster="${team}" style="margin:10px 0 14px">Add Player</button><div class="roster-list">${rows||'<p class="muted">No players added yet.</p>'}</div>`}
function addRoster(team){const num=document.getElementById(team+'Num').value.trim(),name=document.getElementById(team+'Name').value.trim(),position=document.getElementById(team+'Pos').value.trim();if(!num||!name){toast('Enter jersey number and name');return}state.rosters[team].push({id:uid(),number:num,name,position});save();toast('Player added')}

// Navigation & settings
document.querySelectorAll('.tabs button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===btn.dataset.view));renderAll()});
document.getElementById('settingsBtn').onclick=()=>{document.getElementById('syncUrlInput').value=state.settings.syncUrl||'';document.getElementById('publishKeyInput').value=state.settings.publishKey||'';document.getElementById('listenUrlInput').value=state.settings.listenUrl||'';document.getElementById('settingsDialog').showModal()};document.getElementById('saveSettingsBtn').onclick=()=>{state.settings.syncUrl=document.getElementById('syncUrlInput').value.trim();state.settings.publishKey=document.getElementById('publishKeyInput').value.trim();state.settings.listenUrl=document.getElementById('listenUrlInput').value.trim();save();toast('Settings saved')};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
ensureGame();renderAll();
