const API=(window.IRA_PUBLIC_API_URL||'').trim();
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function qlabel(q){return q===1?'1st':q===2?'2nd':q===3?'3rd':q===4?'4th':'OT'}
function setBadge(text,cls=''){const e=document.getElementById('connectionBadge');e.textContent=text;e.className='connection-badge '+cls}
function render(d){if(!d||!d.ok||!d.data){document.getElementById('publicApp').innerHTML=`<div class="card setup-card"><h2>No live game published yet</h2><p class="muted">Once the broadcaster starts publishing, the live scoreboard and play-by-play will appear here automatically.</p></div>`;setBadge('Waiting','stale');return}const x=d.data,g=x.game,s=x.stats||{},ira=s.ira||{},opp=s.opp||{},plays=x.plays||[],latest=plays.length?plays[plays.length-1]:null,age=(Date.now()-new Date(x.updated).getTime())/1000;setBadge(age<45?'LIVE':'Last update '+Math.max(1,Math.round(age/60))+'m ago',age<45?'live':'stale');
 const passRows=(x.leaders?.passing||[]).map(r=>`<tr><td>${esc(r.name)}</td><td class="num">${r.attempts??''}</td><td class="num">${r.value}</td></tr>`).join('');const recRows=(x.leaders?.receiving||[]).map(r=>`<tr><td>${esc(r.name)}</td><td class="num">${r.attempts??''}</td><td class="num">${r.value}</td></tr>`).join('');const leaderRows=(x.leaders?.rushing||[]).map(r=>`<tr><td>${esc(r.name)}</td><td class="num">${r.attempts??''}</td><td class="num">${r.value}</td></tr>`).join('');
 document.getElementById('publicApp').innerHTML=`<div class="card hero"><div class="eyebrow">${g.final?'FINAL':`WEEK ${g.week} • ${qlabel(g.quarter)} ${esc(g.clock)}`}</div><div class="public-score"><div><div class="public-team">IRA</div><div class="public-score-number">${g.iraScore}</div></div><div class="score-dash">–</div><div><div class="public-team">${esc(g.opponent)}</div><div class="public-score-number">${g.oppScore}</div></div></div>${!g.final?`<div class="public-situation">${g.possession==='ira'?'IRA BALL':'OPPONENT BALL'} • ${g.down}${g.down===1?'st':g.down===2?'nd':g.down===3?'rd':'th'} & ${g.toGo} • ${esc(g.ballOn)}</div>`:''}${x.listenUrl?`<a class="listen-btn" href="${esc(x.listenUrl)}" target="_blank" rel="noopener">▶ Listen Live</a>`:''}</div>
 <div class="public-grid"><div class="card"><h2>Latest Play</h2><div class="latest-play">${latest?esc(latest.text):'Waiting for the first play.'}</div><h2 style="margin-top:20px">Team Stats</h2><div class="public-stat-grid"><div class="public-stat"><strong>${ira.totalYds||0}</strong>Total yards</div><div class="public-stat"><strong>${ira.rushYds||0}</strong>Rush yards</div><div class="public-stat"><strong>${ira.passYds||0}</strong>Pass yards</div><div class="public-stat"><strong>${ira.firstDowns||0}</strong>First downs</div><div class="public-stat"><strong>${ira.turnovers||0}</strong>Turnovers</div><div class="public-stat"><strong>${ira.plays||0}</strong>Plays</div></div></div>
 <div class="card"><h2>Ira Rushing Leaders</h2>${leaderRows?`<div class="table-wrap"><table><thead><tr><th>Player</th><th class="num">Car</th><th class="num">Yds</th></tr></thead><tbody>${leaderRows}</tbody></table></div>`:'<p class="muted">Player leaders will appear as stats are entered.</p>'}<h2 style="margin-top:20px">Ira Passing Leaders</h2>${passRows?`<div class="table-wrap"><table><thead><tr><th>Player</th><th class="num">Att</th><th class="num">Yds</th></tr></thead><tbody>${passRows}</tbody></table></div>`:'<p class="muted">No passing stats yet.</p>'}<h2 style="margin-top:20px">Ira Receiving Leaders</h2>${recRows?`<div class="table-wrap"><table><thead><tr><th>Player</th><th class="num">Rec</th><th class="num">Yds</th></tr></thead><tbody>${recRows}</tbody></table></div>`:'<p class="muted">No receiving stats yet.</p>'}<h2 style="margin-top:20px">Game Comparison</h2><div class="table-wrap"><table><thead><tr><th>Stat</th><th class="num">Ira</th><th class="num">Opp</th></tr></thead><tbody><tr><td>Total yards</td><td class="num">${ira.totalYds||0}</td><td class="num">${opp.totalYds||0}</td></tr><tr><td>Rushing</td><td class="num">${ira.rushYds||0}</td><td class="num">${opp.rushYds||0}</td></tr><tr><td>Passing</td><td class="num">${ira.passYds||0}</td><td class="num">${opp.passYds||0}</td></tr><tr><td>Turnovers</td><td class="num">${ira.turnovers||0}</td><td class="num">${opp.turnovers||0}</td></tr></tbody></table></div></div></div>
 <div class="card" style="margin-top:16px"><h2>Play-by-Play</h2><div class="public-playlog">${plays.length?[...plays].reverse().map(p=>`<div class="public-play"><strong>#${p.seq}</strong>${esc(p.text)}</div>`).join(''):'<p class="muted">No plays published yet.</p>'}</div></div>`}
function jsonp(){if(!API){document.getElementById('publicApp').innerHTML=`<div class="card setup-card"><h2>Public Game Center is ready</h2><p>Paste your deployed Google Apps Script <strong>/exec</strong> URL into <code>config.js</code>. Then this page can be embedded on the church website.</p></div>`;setBadge('Setup needed','stale');return}const cb='iraPublic_'+Date.now()+'_'+Math.floor(Math.random()*10000);window[cb]=d=>{try{render(d)}finally{delete window[cb];script.remove()}};const script=document.createElement('script');script.src=API+(API.includes('?')?'&':'?')+'action=public&callback='+encodeURIComponent(cb)+'&_='+Date.now();script.onerror=()=>{setBadge('Connection issue','stale');delete window[cb];script.remove()};document.body.appendChild(script)}
jsonp();setInterval(jsonp,12000);
